
package com.github.pabloo99.xmlsoccer.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FootballDataHttpPost", targetNamespace = "http://xmlsoccer.com/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FootballDataHttpPost {


    /**
     * 
     * @param startDateString
     * @param teamId
     * @param endDateString
     * @param apiKey
     */
    @WebMethod(operationName = "GetHistoricMatchesByTeamAndDateInterval")
    public void getHistoricMatchesByTeamAndDateInterval(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "teamId")
            String teamId,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "startDateString")
            String startDateString,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endDateString")
            String endDateString);

    /**
     * 
     * @param startDateString
     * @param teamId
     * @param endDateString
     * @param apiKey
     */
    @WebMethod(operationName = "GetFixturesByDateIntervalAndTeam")
    public void getFixturesByDateIntervalAndTeam(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "startDateString")
            String startDateString,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endDateString")
            String endDateString,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "teamId")
            String teamId);

    /**
     * 
     * @param seasonDateString
     * @param league
     * @param apiKey
     */
    @WebMethod(operationName = "GetFixturesByLeagueAndSeason")
    public void getFixturesByLeagueAndSeason(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "seasonDateString")
            String seasonDateString,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "league")
            String league);

    /**
     * 
     * @param id
     * @param apiKey
     */
    @WebMethod(operationName = "GetHistoricMatchesByID")
    public void getHistoricMatchesByID(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Id")
            String id);

    /**
     * 
     * @param id
     * @param apiKey
     */
    @WebMethod(operationName = "GetHistoricMatchesByFixtureMatchID")
    public void getHistoricMatchesByFixtureMatchID(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Id")
            String id);

    /**
     * 
     * @param seasonDateString
     * @param league
     * @param apiKey
     */
    @WebMethod(operationName = "GetTopScorersByLeagueAndSeason")
    public void getTopScorersByLeagueAndSeason(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "league")
            String league,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "seasonDateString")
            String seasonDateString);

    /**
     * 
     * @param groupId
     * @param apiKey
     */
    @WebMethod(operationName = "GetTopScorersByGroupId")
    public void getTopScorersByGroupId(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "groupId")
            String groupId);

    /**
     * 
     * @param startDateString
     * @param league
     * @param endDateString
     * @param apiKey
     */
    @WebMethod(operationName = "GetHistoricMatchesByLeagueAndDateInterval")
    public void getHistoricMatchesByLeagueAndDateInterval(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "league")
            String league,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "startDateString")
            String startDateString,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endDateString")
            String endDateString);

    /**
     * 
     * @param seasonDateString
     * @param league
     * @param apiKey
     */
    @WebMethod(operationName = "GetHistoricMatchesByLeagueAndSeason")
    public void getHistoricMatchesByLeagueAndSeason(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "league")
            String league,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "seasonDateString")
            String seasonDateString);

    /**
     * 
     * @param team2Id
     * @param startDateString
     * @param team1Id
     * @param endDateString
     * @param apiKey
     */
    @WebMethod(operationName = "GetHistoricMatchesByTeamsAndDateInterval")
    public void getHistoricMatchesByTeamsAndDateInterval(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "team1Id")
            String team1Id,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "team2Id")
            String team2Id,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "startDateString")
            String startDateString,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endDateString")
            String endDateString);

    /**
     * 
     * @param startDateString
     * @param endDateString
     * @param apiKey
     */
    @WebMethod(operationName = "GetFixturesByDateInterval")
    public void getFixturesByDateInterval(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "startDateString")
            String startDateString,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endDateString")
            String endDateString);

    /**
     * 
     * @param startDateString
     * @param league
     * @param endDateString
     * @param apiKey
     */
    @WebMethod(operationName = "GetFixturesByDateIntervalAndLeague")
    public void getFixturesByDateIntervalAndLeague(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "league")
            String league,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "startDateString")
            String startDateString,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "endDateString")
            String endDateString);

    /**
     * 
     * @param apiKey
     */
    @WebMethod(operationName = "GetAllTeams")
    public void getAllTeams(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey);

    /**
     * 
     * @param apiKey
     */
    @WebMethod(operationName = "GetAllLeagues")
    public void getAllLeagues(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey);

    /**
     * 
     * @param seasonDateString
     * @param league
     * @param apiKey
     */
    @WebMethod(operationName = "GetAllGroupsByLeagueAndSeason")
    public void getAllGroupsByLeagueAndSeason(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "league")
            String league,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "seasonDateString")
            String seasonDateString);

    /**
     * 
     * @param seasonDateString
     * @param league
     * @param apiKey
     */
    @WebMethod(operationName = "GetLeagueStandingsBySeason")
    public void getLeagueStandingsBySeason(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "league")
            String league,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "seasonDateString")
            String seasonDateString);

    /**
     * 
     * @param groupId
     * @param apiKey
     */
    @WebMethod(operationName = "GetCupStandingsByGroupId")
    public void getCupStandingsByGroupId(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "group_Id")
            String groupId);

    /**
     * 
     * @param seasonDateString
     * @param league
     * @param apiKey
     */
    @WebMethod(operationName = "GetAllTeamsByLeagueAndSeason")
    public void getAllTeamsByLeagueAndSeason(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "league")
            String league,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "seasonDateString")
            String seasonDateString);

    /**
     * 
     * @param league
     * @param apiKey
     */
    @WebMethod(operationName = "GetEarliestMatchDatePerLeague")
    public void getEarliestMatchDatePerLeague(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "league")
            String league);

    /**
     * 
     * @param apiKey
     */
    @WebMethod(operationName = "GetLiveScore")
    public void getLiveScore(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey);

    /**
     * 
     * @param league
     * @param apiKey
     */
    @WebMethod(operationName = "GetLiveScoreByLeague")
    public void getLiveScoreByLeague(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "league")
            String league);

    /**
     * 
     * @param teamId
     * @param apiKey
     */
    @WebMethod(operationName = "GetPlayersByTeam")
    public void getPlayersByTeam(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "teamId")
            String teamId);

    /**
     * 
     * @param playerId
     * @param apiKey
     */
    @WebMethod(operationName = "GetPlayerById")
    public void getPlayerById(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "playerId")
            String playerId);

    /**
     * 
     * @param teamName
     * @param apiKey
     */
    @WebMethod(operationName = "GetTeam")
    public void getTeam(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "teamName")
            String teamName);

    /**
     * 
     * @param fixtureMatchId
     * @param apiKey
     */
    @WebMethod(operationName = "GetOddsByFixtureMatchId")
    public void getOddsByFixtureMatchId(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fixtureMatch_Id")
            String fixtureMatchId);

    /**
     * 
     * @param fixtureMatchId
     * @param apiKey
     */
    @WebMethod(operationName = "GetOddsByFixtureMatchId2")
    public void getOddsByFixtureMatchId2(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fixtureMatch_Id")
            String fixtureMatchId);

    /**
     * 
     * @param fixtureMatchId
     * @param apiKey
     */
    @WebMethod(operationName = "GetAllOddsByFixtureMatchId")
    public void getAllOddsByFixtureMatchId(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "fixtureMatch_Id")
            String fixtureMatchId);

    /**
     * 
     * @param league
     * @param apiKey
     */
    @WebMethod(operationName = "GetNextMatchOddsByLeague")
    public void getNextMatchOddsByLeague(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey,
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "league")
            String league);

    /**
     * 
     * @param apiKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CheckApiKey")
    @WebResult(name = "string", targetNamespace = "http://xmlsoccer.com/", partName = "Body")
    public String checkApiKey(
            @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ApiKey")
            String apiKey);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ImAlive")
    @WebResult(name = "string", targetNamespace = "http://xmlsoccer.com/", partName = "Body")
    public String imAlive();

}
