
package com.github.pabloo99.xmlsoccer.webservice;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FootballData", targetNamespace = "http://xmlsoccer.com/", wsdlLocation = "http://www.xmlsoccer.com/FootballData.asmx?WSDL")
public class FootballData
    extends Service
{

    private final static URL FOOTBALLDATA_WSDL_LOCATION;
    private final static WebServiceException FOOTBALLDATA_EXCEPTION;
    private final static QName FOOTBALLDATA_QNAME = new QName("http://xmlsoccer.com/", "FootballData");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://www.xmlsoccer.com/FootballData.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FOOTBALLDATA_WSDL_LOCATION = url;
        FOOTBALLDATA_EXCEPTION = e;
    }

    public FootballData() {
        super(__getWsdlLocation(), FOOTBALLDATA_QNAME);
    }

    public FootballData(WebServiceFeature... features) {
        super(__getWsdlLocation(), FOOTBALLDATA_QNAME, features);
    }

    public FootballData(URL wsdlLocation) {
        super(wsdlLocation, FOOTBALLDATA_QNAME);
    }

    public FootballData(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FOOTBALLDATA_QNAME, features);
    }

    public FootballData(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FootballData(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FootballDataSoap
     */
    @WebEndpoint(name = "FootballDataSoap")
    public FootballDataSoap getFootballDataSoap() {
        return super.getPort(new QName("http://xmlsoccer.com/", "FootballDataSoap"), FootballDataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FootballDataSoap
     */
    @WebEndpoint(name = "FootballDataSoap")
    public FootballDataSoap getFootballDataSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlsoccer.com/", "FootballDataSoap"), FootballDataSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns FootballDataSoap
     */
    @WebEndpoint(name = "FootballDataSoap12")
    public FootballDataSoap getFootballDataSoap12() {
        return super.getPort(new QName("http://xmlsoccer.com/", "FootballDataSoap12"), FootballDataSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FootballDataSoap
     */
    @WebEndpoint(name = "FootballDataSoap12")
    public FootballDataSoap getFootballDataSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlsoccer.com/", "FootballDataSoap12"), FootballDataSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns FootballDataHttpGet
     */
    @WebEndpoint(name = "FootballDataHttpGet")
    public FootballDataHttpGet getFootballDataHttpGet() {
        return super.getPort(new QName("http://xmlsoccer.com/", "FootballDataHttpGet"), FootballDataHttpGet.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FootballDataHttpGet
     */
    @WebEndpoint(name = "FootballDataHttpGet")
    public FootballDataHttpGet getFootballDataHttpGet(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlsoccer.com/", "FootballDataHttpGet"), FootballDataHttpGet.class, features);
    }

    /**
     * 
     * @return
     *     returns FootballDataHttpPost
     */
    @WebEndpoint(name = "FootballDataHttpPost")
    public FootballDataHttpPost getFootballDataHttpPost() {
        return super.getPort(new QName("http://xmlsoccer.com/", "FootballDataHttpPost"), FootballDataHttpPost.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FootballDataHttpPost
     */
    @WebEndpoint(name = "FootballDataHttpPost")
    public FootballDataHttpPost getFootballDataHttpPost(WebServiceFeature... features) {
        return super.getPort(new QName("http://xmlsoccer.com/", "FootballDataHttpPost"), FootballDataHttpPost.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FOOTBALLDATA_EXCEPTION!= null) {
            throw FOOTBALLDATA_EXCEPTION;
        }
        return FOOTBALLDATA_WSDL_LOCATION;
    }

}
