package com.github.pabloo99.xmlsoccer.api.dto;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import javax.xml.datatype.XMLGregorianCalendar;

/**
 * Created by pmazur on 2014-11-30.
 */
@Data
@AllArgsConstructor
@NoArgsConstructor
public class GetOddsResultDto {

    private Integer id;
    private Integer fixtureMatchId;
    private XMLGregorianCalendar dateCreate;
    private String _10BetHomeHome;
    private String _10BetHomeUrl;
    private String _10BetHomeAway;
    private String _10BetHomeDraw;
    private String betAtHomeHome;
    private String betAtHomeUrl;
    private String betAtHomeAway;
    private String betAtHomeDraw;
    private String bet365Url;
    private String bet365Home;
    private String bet365Away;
    private String bet365Draw;
    private String betVictorHome;
    private String betVictorUrl;
    private String betVictorAway;
    private String betVictorDraw;
    private String bwinHome;
    private String bwinUrl;
    private String bwinAway;
    private String bwinDraw;
    private String dafabetHome;
    private String dafabetUrl;
    private String databetAway;
    private String dafabetDraw;
    private String dafabetAway;
    private String ladbrokesHome;
    private String ladbrokesUrl;
    private String ladbrokesAway;
    private String ladbrokesDraw;
    private String marathonBetHome;
    private String marathonBetUrl;
    private String marathonBetAway;
    private String marathonBetDraw;
    private String myBetHome;
    private String myBetUrl;
    private String myBetAway;
    private String myBetDraw;
    private String nordicBetHome;
    private String nordicBetUrl;
    private String nordicBetAway;
    private String nordicBetDraw;
    private String paddyPowerHome;
    private String paddyPowerUrl;
    private String paddyPowerAway;
    private String paddyPowerDraw;
    private String pinnacleSportsHome;
    private String pinnacleSportsUrl;
    private String pinnacleSportsAway;
    private String pinnacleSportsDraw;
    private String sboBetHome;
    private String sboBetUrl;
    private String sboBetAway;
    private String sboBetDraw;
    private String unibetHome;
    private String unibetUrl;
    private String unibetAway;
    private String unibetDraw;
    private String _12BetHome;
    private String _12BetUrl;
    private String _12BetDraw;
    private String _12BetAway;
    private String _188BetHome;
    private String _188BetUrl;
    private String _188BetDraw;
    private String _188BetAway;
    private String _5DimesHome;
    private String _5DimesUrl;
    private String _5DimesDraw;
    private String _5DimesAway;
    private String _888SportHome;
    private String _888SportUrl;
    private String _888SportDraw;
    private String _888SportAway;
    private String bestBetHome;
    private String bestBetUrl;
    private String bestBetDraw;
    private String bestBetAway;
    private String betbooHome;
    private String betbooUrl;
    private String betbooDraw;
    private String betbooAway;
    private String betwayHome;
    private String betwayUrl;
    private String betwayDraw;
    private String betwayAway;
    private String betfairHome;
    private String betfairUrl;
    private String betfairDraw;
    private String betfairAway;
    private String expectHome;
    private String expectDraw;
    private String expectUrl;
    private String expectAway;
    private String betsafeHome;
    private String betsafeUrl;
    private String betsafeDraw;
    private String betsafeAway;
    private String interwettenHome;
    private String interwettenUrl;
    private String interwettenDraw;
    private String interwettenAway;
    private String williamHillHome;
    private String williamHillUrl;
    private String williamHillDraw;
    private String williamHillAway;
    private String betclicHome;
    private String betclicDraw;
    private String betclicAway;
    private String betclicUrl;
    private String blueSquareHome;
    private String blueSquareDraw;
    private String blueSquareAway;
    private String blueSquareUrl;
    private String canBetHome;
    private String canBetDraw;
    private String canBetAway;
    private String canBetUrl;
    private String comeOnHome;
    private String comeOnDraw;
    private String comeOnAway;
    private String comeOnUrl;
    private String coralHome;
    private String coralDraw;
    private String coralAway;
    private String coralUrl;
    private String doxXbetHome;
    private String doxXbetDraw;
    private String doxXbetAway;
    private String doxXbetUrl;
    private String fortunaWinHome;
    private String fortunaWinDraw;
    private String fortunaWinAway;
    private String fortunaWinUrl;
    private String tipicoHome;
    private String tipicoDraw;
    private String tipicoAway;
    private String tipicoUrl;
}
