package pl.com.pablo.xmlsoccer.model.xml;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.01 at 08:11:35 AM CEST 
//


import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Team" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Team_Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Stadium" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HomePageURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="WIKILink" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AccountInformation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "team",
    "accountInformation"
})
@XmlRootElement(name = "XMLSOCCER.COM")
public class GetAllTeamsResultXML {

    @XmlElement(name = "Team")
    protected List<Team> team;
    @XmlElement(name = "AccountInformation", required = true)
    protected String accountInformation;

    /**
     * Gets the value of the team property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the team property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTeam().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLSOCCERCOM.Team }
     *
     *
     */
    public List<Team> getTeam() {
        if (team == null) {
            team = new ArrayList<Team>();
        }
        return this.team;
    }

    /**
     * Gets the value of the accountInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountInformation() {
        return accountInformation;
    }

    /**
     * Sets the value of the accountInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountInformation(String value) {
        this.accountInformation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Team_Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Stadium" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HomePageURL" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="WIKILink" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "teamId",
        "name",
        "country",
        "stadium",
        "homePageURL",
        "wikiLink"
    })
    public static class Team {

        @XmlElement(name = "Team_Id")
        protected int teamId;
        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "Country", required = true)
        protected String country;
        @XmlElement(name = "Stadium", required = true)
        protected String stadium;
        @XmlElement(name = "HomePageURL", required = true)
        protected String homePageURL;
        @XmlElement(name = "WIKILink", required = true)
        protected String wikiLink;

        /**
         * Gets the value of the teamId property.
         * 
         */
        public int getTeamId() {
            return teamId;
        }

        /**
         * Sets the value of the teamId property.
         * 
         */
        public void setTeamId(int value) {
            this.teamId = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

        /**
         * Gets the value of the stadium property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStadium() {
            return stadium;
        }

        /**
         * Sets the value of the stadium property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStadium(String value) {
            this.stadium = value;
        }

        /**
         * Gets the value of the homePageURL property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomePageURL() {
            return homePageURL;
        }

        /**
         * Sets the value of the homePageURL property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomePageURL(String value) {
            this.homePageURL = value;
        }

        /**
         * Gets the value of the wikiLink property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWikiLink() {
            return wikiLink;
        }

        /**
         * Sets the value of the wikiLink property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWikiLink(String value) {
            this.wikiLink = value;
        }

        @Override
        public String toString() {
//            return "Team{" + "teamId=" + teamId + ", name=" + name + ", country=" + country + ", stadium=" + stadium + ", homePageURL=" + homePageURL + ", wikiLink=" + wikiLink + '}';
            return "TEAM: " + "  NAME: " + name + "  COUNTRY: " + country + "  STADIUM: " + stadium + "  HOME PAGE: " + homePageURL;
        }


    }

}
