package pl.com.pablo.xmlsoccer.model.xml;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.01 at 12:25:16 AM CEST 
//


import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="League" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Historical_Data" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Fixtures" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Livescore" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="NumberOfMatches" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="LatestMatch" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AccountInformation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "league",
    "accountInformation"
})
@XmlRootElement(name = "XMLSOCCER.COM")
public class GetAllLeaguesResultXML {

    @XmlElement(name = "League")
    protected List<League> league;
    @XmlElement(name = "AccountInformation", required = true)
    protected String accountInformation;

    /**
     * Gets the value of the league property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * T        his is why there is not a <CODE>set</CODE> method for the league property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLeague().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLSOCCERCOM.League }
     *
     *
     */
    public List<League> getLeague() {
        if (league == null) {
            league = new ArrayList<League>();
        }
        return this.league;
    }

    /**
     * Gets the value of the accountInformation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAccountInformation() {
        return accountInformation;
    }

    /**
     * Sets the value of the accountInformation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAccountInformation(String value) {
        this.accountInformation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Historical_Data" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Fixtures" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Livescore" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="NumberOfMatches" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="LatestMatch" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "name",
        "country",
        "historicalData",
        "fixtures",
        "livescore",
        "numberOfMatches",
        "latestMatch"
    })
    public static class League {

        @XmlElement(name = "Id")
        protected int id;
        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "Country", required = true)
        protected String country;
        @XmlElement(name = "Historical_Data", required = true)
        protected String historicalData;
        @XmlElement(name = "Fixtures", required = true)
        protected String fixtures;
        @XmlElement(name = "Livescore", required = true)
        protected String livescore;
        @XmlElement(name = "NumberOfMatches")
        protected int numberOfMatches;
        @XmlElement(name = "LatestMatch", required = true)
        @XmlSchemaType(name = "dateTime")
        protected Date latestMatch;

        /**
         * Gets the value of the id property.
         *
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         *
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the name property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the country property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setCountry(String value) {
            this.country = value;
        }

        /**
         * Gets the value of the historicalData property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getHistoricalData() {
            return historicalData;
        }

        /**
         * Sets the value of the historicalData property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setHistoricalData(String value) {
            this.historicalData = value;
        }

        /**
         * Gets the value of the fixtures property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getFixtures() {
            return fixtures;
        }

        /**
         * Sets the value of the fixtures property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setFixtures(String value) {
            this.fixtures = value;
        }

        /**
         * Gets the value of the livescore property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getLivescore() {
            return livescore;
        }

        /**
         * Sets the value of the livescore property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setLivescore(String value) {
            this.livescore = value;
        }

        /**
         * Gets the value of the numberOfMatches property.
         *
         */
        public int getNumberOfMatches() {
            return numberOfMatches;
        }

        /**
         * Sets the value of the numberOfMatches property.
         *
         */
        public void setNumberOfMatches(int value) {
            this.numberOfMatches = value;
        }

        /**
         * Gets the value of the latestMatch property.
         *
         * @return
         *     possible object is
         *     {@link javax.xml.datatype.XMLGregorianCalendar }
         *
         */
        public Date getLatestMatch() {
            return latestMatch;
        }

        /**
         * Sets the value of the latestMatch property.
         *
         * @param value
         *     allowed object is
         *     {@link javax.xml.datatype.XMLGregorianCalendar }
         *     
         */
        public void setLatestMatch(Date value) {
            this.latestMatch = value;
        }

        @Override
        public String toString() {
//            return "League{" + "id=" + id + ", name=" + name + ", country=" + country + ", historicalData=" + historicalData + ", fixtures=" + fixtures + ", livescore=" + livescore + ", numberOfMatches=" + numberOfMatches + ", latestMatch=" + latestMatch + '}';
            return "LEAGUES: " + "  NAME: " + name + "  COUNTRY: " + country + "  HISTORICAL DATA: " + historicalData + "  FIXTURES: " + fixtures + "  LIVESCORE: " + livescore + "  NUMBER OF MATCHES: " + numberOfMatches + "  LASTEST MATCHES: " + latestMatch;
        }
        
        

    }

}
