//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.01 at 12:08:02 AM CEST 
//


package pl.com.pablo.xmlsoccer.model.xml;


import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Match" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="League" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Round" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Spectators" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Hometeam" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HomeTeam_Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Awayteam" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AwayTeam_Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HomeGoals" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="AwayGoals" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="HomeGoalDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AwayGoalDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HomeLineupGoalkeeper" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AwayLineupGoalkeeper" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HomeLineupDefense" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AwayLineupDefense" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HomeLineupMidfield" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AwayLineupMidfield" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HomeLineupForward" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AwayLineupForward" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HomeSubDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AwaySubDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HomeTeamFormation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AwayTeamFormation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Stadium" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HomeTeamYellowCardDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AwayTeamYellowCardDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HomeTeamRedCardDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AwayTeamRedCardDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AccountInformation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "match",
    "accountInformation"
})
@XmlRootElement(name = "XMLSOCCER.COM")
public class GetLiveScoreResultXML {

    @XmlElement(name = "Match")
    protected List<Match> match;
    @XmlElement(name = "AccountInformation", required = true)
    protected String accountInformation;

    /**
     * Gets the value of the match property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the match property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMatch().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLSOCCERCOM.Match }
     *
     *
     */
    public List<Match> getMatch() {
        if (match == null) {
            match = new ArrayList<Match>();
        }
        return this.match;
    }

    /**
     * Gets the value of the accountInformation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAccountInformation() {
        return accountInformation;
    }

    /**
     * Sets the value of the accountInformation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAccountInformation(String value) {
        this.accountInformation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="League" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Round" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Spectators" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Hometeam" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HomeTeam_Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Awayteam" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AwayTeam_Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HomeGoals" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="AwayGoals" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="HomeGoalDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AwayGoalDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HomeLineupGoalkeeper" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AwayLineupGoalkeeper" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HomeLineupDefense" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AwayLineupDefense" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HomeLineupMidfield" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AwayLineupMidfield" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HomeLineupForward" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AwayLineupForward" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HomeSubDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AwaySubDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HomeTeamFormation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AwayTeamFormation" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Stadium" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HomeTeamYellowCardDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AwayTeamYellowCardDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HomeTeamRedCardDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AwayTeamRedCardDetails" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "date",
        "league",
        "round",
        "spectators",
        "hometeam",
        "homeTeamId",
        "awayteam",
        "awayTeamId",
        "time",
        "homeGoals",
        "awayGoals",
        "homeGoalDetails",
        "awayGoalDetails",
        "homeLineupGoalkeeper",
        "awayLineupGoalkeeper",
        "homeLineupDefense",
        "awayLineupDefense",
        "homeLineupMidfield",
        "awayLineupMidfield",
        "homeLineupForward",
        "awayLineupForward",
        "homeSubDetails",
        "awaySubDetails",
        "homeTeamFormation",
        "awayTeamFormation",
        "location",
        "stadium",
        "homeTeamYellowCardDetails",
        "awayTeamYellowCardDetails",
        "homeTeamRedCardDetails",
        "awayTeamRedCardDetails",
        "awayLineupCoach",
        "homeLineupCoach",
        "awayLineupSubstitutes",
        "homeLineupSubstitutes"
    })
    public static class Match {

        @XmlElement(name = "Id")
        protected int id;
        @XmlElement(name = "Date", required = true)
        @XmlSchemaType(name = "dateTime")
        protected Date date;
        @XmlElement(name = "League", required = true)
        protected String league;
        @XmlElement(name = "Round")
        protected String round;
        @XmlElement(name = "Spectators", required = true)
        protected String spectators;
        @XmlElement(name = "Hometeam", required = true)
        protected String hometeam;
        @XmlElement(name = "HomeTeam_Id")
        protected int homeTeamId;
        @XmlElement(name = "Awayteam", required = true)
        protected String awayteam;
        @XmlElement(name = "AwayTeam_Id")
        protected int awayTeamId;
        @XmlElement(name = "Time", required = true)
        protected String time;
        @XmlElement(name = "HomeGoals")
        protected int homeGoals;
        @XmlElement(name = "AwayGoals")
        protected int awayGoals;
        @XmlElement(name = "HomeGoalDetails", required = true)
        protected String homeGoalDetails;
        @XmlElement(name = "AwayGoalDetails", required = true)
        protected String awayGoalDetails;
        @XmlElement(name = "HomeLineupGoalkeeper", required = true)
        protected String homeLineupGoalkeeper;
        @XmlElement(name = "AwayLineupGoalkeeper", required = true)
        protected String awayLineupGoalkeeper;
        @XmlElement(name = "HomeLineupDefense", required = true)
        protected String homeLineupDefense;
        @XmlElement(name = "AwayLineupDefense", required = true)
        protected String awayLineupDefense;
        @XmlElement(name = "HomeLineupMidfield", required = true)
        protected String homeLineupMidfield;
        @XmlElement(name = "AwayLineupMidfield", required = true)
        protected String awayLineupMidfield;
        @XmlElement(name = "HomeLineupForward", required = true)
        protected String homeLineupForward;
        @XmlElement(name = "AwayLineupForward", required = true)
        protected String awayLineupForward;
        @XmlElement(name = "HomeSubDetails", required = true)
        protected String homeSubDetails;
        @XmlElement(name = "AwaySubDetails", required = true)
        protected String awaySubDetails;
        @XmlElement(name = "HomeTeamFormation", required = true)
        protected String homeTeamFormation;
        @XmlElement(name = "AwayTeamFormation", required = true)
        protected String awayTeamFormation;
        @XmlElement(name = "Location", required = true)
        protected String location;
        @XmlElement(name = "Stadium", required = true)
        protected String stadium;
        @XmlElement(name = "HomeTeamYellowCardDetails", required = true)
        protected String homeTeamYellowCardDetails;
        @XmlElement(name = "AwayTeamYellowCardDetails", required = true)
        protected String awayTeamYellowCardDetails;
        @XmlElement(name = "HomeTeamRedCardDetails", required = true)
        protected String homeTeamRedCardDetails;
        @XmlElement(name = "AwayTeamRedCardDetails", required = true)
        protected String awayTeamRedCardDetails;
        @XmlElement(name = "HomeLineupCoach", required = true)
        protected String homeLineupCoach;
        @XmlElement(name = "AwayLineupCoach", required = true)
        protected String awayLineupCoach;
        @XmlElement(name = "HomeLineupSubstitutes", required = true)
        protected String homeLineupSubstitutes;
        @XmlElement(name = "AwayLineupSubstitutes", required = true)
        protected String awayLineupSubstitutes;

        public String getHomeLineupCoach() {
            return homeLineupCoach;
        }

        public void setHomeLineupCoach(String homeLineupCoach) {
            this.homeLineupCoach = homeLineupCoach;
        }

        public String getAwayLineupCoach() {
            return awayLineupCoach;
        }

        public void setAwayLineupCoach(String awayLineupCoach) {
            this.awayLineupCoach = awayLineupCoach;
        }

        public String getHomeLineupSubstitutes() {
            return homeLineupSubstitutes;
        }

        public void setHomeLineupSubstitutes(String homeLineupSubstitutes) {
            this.homeLineupSubstitutes = homeLineupSubstitutes;
        }

        public String getAwayLineupSubstitutes() {
            return awayLineupSubstitutes;
        }

        public void setAwayLineupSubstitutes(String awayLineupSubstitutes) {
            this.awayLineupSubstitutes = awayLineupSubstitutes;
        }

        /**
         * Gets the value of the id property.
         *
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         *
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the date property.
         *
         * @return
         *     possible object is
         *     {@link javax.xml.datatype.XMLGregorianCalendar }
         *
         */
        public Date getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         *
         * @param value
         *     allowed object is
         *     {@link javax.xml.datatype.XMLGregorianCalendar }
         *     
         */
        public void setDate(Date value) {
            this.date = value;
        }

        /**
         * Gets the value of the league property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLeague() {
            return league;
        }

        /**
         * Sets the value of the league property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLeague(String value) {
            this.league = value;
        }

        /**
         * Gets the value of the round property.
         * 
         */
        public String getRound() {
            return round;
        }

        /**
         * Sets the value of the round property.
         * 
         */
        public void setRound(String value) {
            this.round = value;
        }

        /**
         * Gets the value of the spectators property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpectators() {
            return spectators;
        }

        /**
         * Sets the value of the spectators property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpectators(String value) {
            this.spectators = value;
        }

        /**
         * Gets the value of the hometeam property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHometeam() {
            return hometeam;
        }

        /**
         * Sets the value of the hometeam property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHometeam(String value) {
            this.hometeam = value;
        }

        /**
         * Gets the value of the homeTeamId property.
         * 
         */
        public int getHomeTeamId() {
            return homeTeamId;
        }

        /**
         * Sets the value of the homeTeamId property.
         * 
         */
        public void setHomeTeamId(int value) {
            this.homeTeamId = value;
        }

        /**
         * Gets the value of the awayteam property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayteam() {
            return awayteam;
        }

        /**
         * Sets the value of the awayteam property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayteam(String value) {
            this.awayteam = value;
        }

        /**
         * Gets the value of the awayTeamId property.
         * 
         */
        public int getAwayTeamId() {
            return awayTeamId;
        }

        /**
         * Sets the value of the awayTeamId property.
         * 
         */
        public void setAwayTeamId(int value) {
            this.awayTeamId = value;
        }

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTime() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTime(String value) {
            this.time = value;
        }

        /**
         * Gets the value of the homeGoals property.
         * 
         */
        public int getHomeGoals() {
            return homeGoals;
        }

        /**
         * Sets the value of the homeGoals property.
         * 
         */
        public void setHomeGoals(int value) {
            this.homeGoals = value;
        }

        /**
         * Gets the value of the awayGoals property.
         * 
         */
        public int getAwayGoals() {
            return awayGoals;
        }

        /**
         * Sets the value of the awayGoals property.
         * 
         */
        public void setAwayGoals(int value) {
            this.awayGoals = value;
        }

        /**
         * Gets the value of the homeGoalDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeGoalDetails() {
            return homeGoalDetails;
        }

        /**
         * Sets the value of the homeGoalDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeGoalDetails(String value) {
            this.homeGoalDetails = value;
        }

        /**
         * Gets the value of the awayGoalDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayGoalDetails() {
            return awayGoalDetails;
        }

        /**
         * Sets the value of the awayGoalDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayGoalDetails(String value) {
            this.awayGoalDetails = value;
        }

        /**
         * Gets the value of the homeLineupGoalkeeper property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeLineupGoalkeeper() {
            return homeLineupGoalkeeper;
        }

        /**
         * Sets the value of the homeLineupGoalkeeper property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeLineupGoalkeeper(String value) {
            this.homeLineupGoalkeeper = value;
        }

        /**
         * Gets the value of the awayLineupGoalkeeper property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayLineupGoalkeeper() {
            return awayLineupGoalkeeper;
        }

        /**
         * Sets the value of the awayLineupGoalkeeper property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayLineupGoalkeeper(String value) {
            this.awayLineupGoalkeeper = value;
        }

        /**
         * Gets the value of the homeLineupDefense property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeLineupDefense() {
            return homeLineupDefense;
        }

        /**
         * Sets the value of the homeLineupDefense property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeLineupDefense(String value) {
            this.homeLineupDefense = value;
        }

        /**
         * Gets the value of the awayLineupDefense property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayLineupDefense() {
            return awayLineupDefense;
        }

        /**
         * Sets the value of the awayLineupDefense property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayLineupDefense(String value) {
            this.awayLineupDefense = value;
        }

        /**
         * Gets the value of the homeLineupMidfield property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeLineupMidfield() {
            return homeLineupMidfield;
        }

        /**
         * Sets the value of the homeLineupMidfield property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeLineupMidfield(String value) {
            this.homeLineupMidfield = value;
        }

        /**
         * Gets the value of the awayLineupMidfield property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayLineupMidfield() {
            return awayLineupMidfield;
        }

        /**
         * Sets the value of the awayLineupMidfield property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayLineupMidfield(String value) {
            this.awayLineupMidfield = value;
        }

        /**
         * Gets the value of the homeLineupForward property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeLineupForward() {
            return homeLineupForward;
        }

        /**
         * Sets the value of the homeLineupForward property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeLineupForward(String value) {
            this.homeLineupForward = value;
        }

        /**
         * Gets the value of the awayLineupForward property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayLineupForward() {
            return awayLineupForward;
        }

        /**
         * Sets the value of the awayLineupForward property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayLineupForward(String value) {
            this.awayLineupForward = value;
        }

        /**
         * Gets the value of the homeSubDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeSubDetails() {
            return homeSubDetails;
        }

        /**
         * Sets the value of the homeSubDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeSubDetails(String value) {
            this.homeSubDetails = value;
        }

        /**
         * Gets the value of the awaySubDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwaySubDetails() {
            return awaySubDetails;
        }

        /**
         * Sets the value of the awaySubDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwaySubDetails(String value) {
            this.awaySubDetails = value;
        }

        /**
         * Gets the value of the homeTeamFormation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeTeamFormation() {
            return homeTeamFormation;
        }

        /**
         * Sets the value of the homeTeamFormation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeTeamFormation(String value) {
            this.homeTeamFormation = value;
        }

        /**
         * Gets the value of the awayTeamFormation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayTeamFormation() {
            return awayTeamFormation;
        }

        /**
         * Sets the value of the awayTeamFormation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayTeamFormation(String value) {
            this.awayTeamFormation = value;
        }

        /**
         * Gets the value of the location property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocation() {
            return location;
        }

        /**
         * Sets the value of the location property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocation(String value) {
            this.location = value;
        }

        /**
         * Gets the value of the stadium property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStadium() {
            return stadium;
        }

        /**
         * Sets the value of the stadium property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStadium(String value) {
            this.stadium = value;
        }

        /**
         * Gets the value of the homeTeamYellowCardDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeTeamYellowCardDetails() {
            return homeTeamYellowCardDetails;
        }

        /**
         * Sets the value of the homeTeamYellowCardDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeTeamYellowCardDetails(String value) {
            this.homeTeamYellowCardDetails = value;
        }

        /**
         * Gets the value of the awayTeamYellowCardDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayTeamYellowCardDetails() {
            return awayTeamYellowCardDetails;
        }

        /**
         * Sets the value of the awayTeamYellowCardDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayTeamYellowCardDetails(String value) {
            this.awayTeamYellowCardDetails = value;
        }

        /**
         * Gets the value of the homeTeamRedCardDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeTeamRedCardDetails() {
            return homeTeamRedCardDetails;
        }

        /**
         * Sets the value of the homeTeamRedCardDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeTeamRedCardDetails(String value) {
            this.homeTeamRedCardDetails = value;
        }

        /**
         * Gets the value of the awayTeamRedCardDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayTeamRedCardDetails() {
            return awayTeamRedCardDetails;
        }

        /**
         * Sets the value of the awayTeamRedCardDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayTeamRedCardDetails(String value) {
            this.awayTeamRedCardDetails = value;
        }

        @Override
        public String toString() {
            //return "Match{" + "id=" + id + ", date=" + date + ", league=" + league + ", round=" + round + ", spectators=" + spectators + ", hometeam=" + hometeam + ", homeTeamId=" + homeTeamId + ", awayteam=" + awayteam + ", awayTeamId=" + awayTeamId + ", time=" + time + ", homeGoals=" + homeGoals + ", awayGoals=" + awayGoals + ", homeGoalDetails=" + homeGoalDetails + ", awayGoalDetails=" + awayGoalDetails + ", homeLineupGoalkeeper=" + homeLineupGoalkeeper + ", awayLineupGoalkeeper=" + awayLineupGoalkeeper + ", homeLineupDefense=" + homeLineupDefense + ", awayLineupDefense=" + awayLineupDefense + ", homeLineupMidfield=" + homeLineupMidfield + ", awayLineupMidfield=" + awayLineupMidfield + ", homeLineupForward=" + homeLineupForward + ", awayLineupForward=" + awayLineupForward + ", homeSubDetails=" + homeSubDetails + ", awaySubDetails=" + awaySubDetails + ", homeTeamFormation=" + homeTeamFormation + ", awayTeamFormation=" + awayTeamFormation + ", location=" + location + ", stadium=" + stadium + ", homeTeamYellowCardDetails=" + homeTeamYellowCardDetails + ", awayTeamYellowCardDetails=" + awayTeamYellowCardDetails + ", homeTeamRedCardDetails=" + homeTeamRedCardDetails + ", awayTeamRedCardDetails=" + awayTeamRedCardDetails + '}';
            return "MATCH: " + "  DATE: " + date + "  LEAGUE: " + league + "  HOME TEAM: " + hometeam + "  AWAY TEAM: " + awayteam + " TIME: " + time + "  HOME GOALS:" + homeGoals + "  AWAY GOALS: " + awayGoals ;
        }

    }

}
