
package pl.com.pablo.xmlsoccer.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FootballDataSoap", targetNamespace = "http://xmlsoccer.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FootballDataSoap {


    /**
     * 
     * @param startDateString
     * @param teamId
     * @param endDateString
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetHistoricMatchesByTeamAndDateIntervalResponse.GetHistoricMatchesByTeamAndDateIntervalResult
     */
    @WebMethod(operationName = "GetHistoricMatchesByTeamAndDateInterval", action = "http://xmlsoccer.com/GetHistoricMatchesByTeamAndDateInterval")
    @WebResult(name = "GetHistoricMatchesByTeamAndDateIntervalResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetHistoricMatchesByTeamAndDateInterval", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetHistoricMatchesByTeamAndDateInterval")
    @ResponseWrapper(localName = "GetHistoricMatchesByTeamAndDateIntervalResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetHistoricMatchesByTeamAndDateIntervalResponse")
    public GetHistoricMatchesByTeamAndDateIntervalResponse.GetHistoricMatchesByTeamAndDateIntervalResult getHistoricMatchesByTeamAndDateInterval(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "teamId", targetNamespace = "http://xmlsoccer.com/")
            String teamId,
            @WebParam(name = "startDateString", targetNamespace = "http://xmlsoccer.com/")
            String startDateString,
            @WebParam(name = "endDateString", targetNamespace = "http://xmlsoccer.com/")
            String endDateString);

    /**
     * 
     * @param startDateString
     * @param teamId
     * @param endDateString
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetFixturesByDateIntervalAndTeamResponse.GetFixturesByDateIntervalAndTeamResult
     */
    @WebMethod(operationName = "GetFixturesByDateIntervalAndTeam", action = "http://xmlsoccer.com/GetFixturesByDateIntervalAndTeam")
    @WebResult(name = "GetFixturesByDateIntervalAndTeamResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetFixturesByDateIntervalAndTeam", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetFixturesByDateIntervalAndTeam")
    @ResponseWrapper(localName = "GetFixturesByDateIntervalAndTeamResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetFixturesByDateIntervalAndTeamResponse")
    public GetFixturesByDateIntervalAndTeamResponse.GetFixturesByDateIntervalAndTeamResult getFixturesByDateIntervalAndTeam(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "startDateString", targetNamespace = "http://xmlsoccer.com/")
            String startDateString,
            @WebParam(name = "endDateString", targetNamespace = "http://xmlsoccer.com/")
            String endDateString,
            @WebParam(name = "teamId", targetNamespace = "http://xmlsoccer.com/")
            String teamId);

    /**
     * 
     * @param seasonDateString
     * @param league
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetFixturesByLeagueAndSeasonResponse.GetFixturesByLeagueAndSeasonResult
     */
    @WebMethod(operationName = "GetFixturesByLeagueAndSeason", action = "http://xmlsoccer.com/GetFixturesByLeagueAndSeason")
    @WebResult(name = "GetFixturesByLeagueAndSeasonResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetFixturesByLeagueAndSeason", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetFixturesByLeagueAndSeason")
    @ResponseWrapper(localName = "GetFixturesByLeagueAndSeasonResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetFixturesByLeagueAndSeasonResponse")
    public GetFixturesByLeagueAndSeasonResponse.GetFixturesByLeagueAndSeasonResult getFixturesByLeagueAndSeason(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "seasonDateString", targetNamespace = "http://xmlsoccer.com/")
            String seasonDateString,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league);

    /**
     * 
     * @param id
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetHistoricMatchesByIDResponse.GetHistoricMatchesByIDResult
     */
    @WebMethod(operationName = "GetHistoricMatchesByID", action = "http://xmlsoccer.com/GetHistoricMatchesByID")
    @WebResult(name = "GetHistoricMatchesByIDResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetHistoricMatchesByID", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetHistoricMatchesByID")
    @ResponseWrapper(localName = "GetHistoricMatchesByIDResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetHistoricMatchesByIDResponse")
    public GetHistoricMatchesByIDResponse.GetHistoricMatchesByIDResult getHistoricMatchesByID(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "Id", targetNamespace = "http://xmlsoccer.com/")
            int id);

    /**
     * 
     * @param id
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetHistoricMatchesByFixtureMatchIDResponse.GetHistoricMatchesByFixtureMatchIDResult
     */
    @WebMethod(operationName = "GetHistoricMatchesByFixtureMatchID", action = "http://xmlsoccer.com/GetHistoricMatchesByFixtureMatchID")
    @WebResult(name = "GetHistoricMatchesByFixtureMatchIDResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetHistoricMatchesByFixtureMatchID", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetHistoricMatchesByFixtureMatchID")
    @ResponseWrapper(localName = "GetHistoricMatchesByFixtureMatchIDResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetHistoricMatchesByFixtureMatchIDResponse")
    public GetHistoricMatchesByFixtureMatchIDResponse.GetHistoricMatchesByFixtureMatchIDResult getHistoricMatchesByFixtureMatchID(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "Id", targetNamespace = "http://xmlsoccer.com/")
            int id);

    /**
     * 
     * @param seasonDateString
     * @param league
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetTopScorersByLeagueAndSeasonResponse.GetTopScorersByLeagueAndSeasonResult
     */
    @WebMethod(operationName = "GetTopScorersByLeagueAndSeason", action = "http://xmlsoccer.com/GetTopScorersByLeagueAndSeason")
    @WebResult(name = "GetTopScorersByLeagueAndSeasonResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetTopScorersByLeagueAndSeason", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetTopScorersByLeagueAndSeason")
    @ResponseWrapper(localName = "GetTopScorersByLeagueAndSeasonResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetTopScorersByLeagueAndSeasonResponse")
    public GetTopScorersByLeagueAndSeasonResponse.GetTopScorersByLeagueAndSeasonResult getTopScorersByLeagueAndSeason(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league,
            @WebParam(name = "seasonDateString", targetNamespace = "http://xmlsoccer.com/")
            String seasonDateString);

    /**
     * 
     * @param groupId
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetTopScorersByGroupIdResponse.GetTopScorersByGroupIdResult
     */
    @WebMethod(operationName = "GetTopScorersByGroupId", action = "http://xmlsoccer.com/GetTopScorersByGroupId")
    @WebResult(name = "GetTopScorersByGroupIdResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetTopScorersByGroupId", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetTopScorersByGroupId")
    @ResponseWrapper(localName = "GetTopScorersByGroupIdResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetTopScorersByGroupIdResponse")
    public GetTopScorersByGroupIdResponse.GetTopScorersByGroupIdResult getTopScorersByGroupId(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "groupId", targetNamespace = "http://xmlsoccer.com/")
            int groupId);

    /**
     * 
     * @param startDateString
     * @param league
     * @param endDateString
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetHistoricMatchesByLeagueAndDateIntervalResponse.GetHistoricMatchesByLeagueAndDateIntervalResult
     */
    @WebMethod(operationName = "GetHistoricMatchesByLeagueAndDateInterval", action = "http://xmlsoccer.com/GetHistoricMatchesByLeagueAndDateInterval")
    @WebResult(name = "GetHistoricMatchesByLeagueAndDateIntervalResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetHistoricMatchesByLeagueAndDateInterval", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetHistoricMatchesByLeagueAndDateInterval")
    @ResponseWrapper(localName = "GetHistoricMatchesByLeagueAndDateIntervalResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetHistoricMatchesByLeagueAndDateIntervalResponse")
    public GetHistoricMatchesByLeagueAndDateIntervalResponse.GetHistoricMatchesByLeagueAndDateIntervalResult getHistoricMatchesByLeagueAndDateInterval(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league,
            @WebParam(name = "startDateString", targetNamespace = "http://xmlsoccer.com/")
            String startDateString,
            @WebParam(name = "endDateString", targetNamespace = "http://xmlsoccer.com/")
            String endDateString);

    /**
     * 
     * @param seasonDateString
     * @param league
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetHistoricMatchesByLeagueAndSeasonResponse.GetHistoricMatchesByLeagueAndSeasonResult
     */
    @WebMethod(operationName = "GetHistoricMatchesByLeagueAndSeason", action = "http://xmlsoccer.com/GetHistoricMatchesByLeagueAndSeason")
    @WebResult(name = "GetHistoricMatchesByLeagueAndSeasonResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetHistoricMatchesByLeagueAndSeason", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetHistoricMatchesByLeagueAndSeason")
    @ResponseWrapper(localName = "GetHistoricMatchesByLeagueAndSeasonResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetHistoricMatchesByLeagueAndSeasonResponse")
    public GetHistoricMatchesByLeagueAndSeasonResponse.GetHistoricMatchesByLeagueAndSeasonResult getHistoricMatchesByLeagueAndSeason(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league,
            @WebParam(name = "seasonDateString", targetNamespace = "http://xmlsoccer.com/")
            String seasonDateString);

    /**
     * 
     * @param team2Id
     * @param startDateString
     * @param team1Id
     * @param endDateString
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetHistoricMatchesByTeamsAndDateIntervalResponse.GetHistoricMatchesByTeamsAndDateIntervalResult
     */
    @WebMethod(operationName = "GetHistoricMatchesByTeamsAndDateInterval", action = "http://xmlsoccer.com/GetHistoricMatchesByTeamsAndDateInterval")
    @WebResult(name = "GetHistoricMatchesByTeamsAndDateIntervalResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetHistoricMatchesByTeamsAndDateInterval", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetHistoricMatchesByTeamsAndDateInterval")
    @ResponseWrapper(localName = "GetHistoricMatchesByTeamsAndDateIntervalResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetHistoricMatchesByTeamsAndDateIntervalResponse")
    public GetHistoricMatchesByTeamsAndDateIntervalResponse.GetHistoricMatchesByTeamsAndDateIntervalResult getHistoricMatchesByTeamsAndDateInterval(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "team1Id", targetNamespace = "http://xmlsoccer.com/")
            String team1Id,
            @WebParam(name = "team2Id", targetNamespace = "http://xmlsoccer.com/")
            String team2Id,
            @WebParam(name = "startDateString", targetNamespace = "http://xmlsoccer.com/")
            String startDateString,
            @WebParam(name = "endDateString", targetNamespace = "http://xmlsoccer.com/")
            String endDateString);

    /**
     * 
     * @param startDateString
     * @param endDateString
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetFixturesByDateIntervalResponse.GetFixturesByDateIntervalResult
     */
    @WebMethod(operationName = "GetFixturesByDateInterval", action = "http://xmlsoccer.com/GetFixturesByDateInterval")
    @WebResult(name = "GetFixturesByDateIntervalResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetFixturesByDateInterval", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetFixturesByDateInterval")
    @ResponseWrapper(localName = "GetFixturesByDateIntervalResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetFixturesByDateIntervalResponse")
    public GetFixturesByDateIntervalResponse.GetFixturesByDateIntervalResult getFixturesByDateInterval(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "startDateString", targetNamespace = "http://xmlsoccer.com/")
            String startDateString,
            @WebParam(name = "endDateString", targetNamespace = "http://xmlsoccer.com/")
            String endDateString);

    /**
     * 
     * @param startDateString
     * @param league
     * @param endDateString
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetFixturesByDateIntervalAndLeagueResponse.GetFixturesByDateIntervalAndLeagueResult
     */
    @WebMethod(operationName = "GetFixturesByDateIntervalAndLeague", action = "http://xmlsoccer.com/GetFixturesByDateIntervalAndLeague")
    @WebResult(name = "GetFixturesByDateIntervalAndLeagueResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetFixturesByDateIntervalAndLeague", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetFixturesByDateIntervalAndLeague")
    @ResponseWrapper(localName = "GetFixturesByDateIntervalAndLeagueResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetFixturesByDateIntervalAndLeagueResponse")
    public GetFixturesByDateIntervalAndLeagueResponse.GetFixturesByDateIntervalAndLeagueResult getFixturesByDateIntervalAndLeague(
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league,
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "startDateString", targetNamespace = "http://xmlsoccer.com/")
            String startDateString,
            @WebParam(name = "endDateString", targetNamespace = "http://xmlsoccer.com/")
            String endDateString);

    /**
     * 
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetAllTeamsResponse.GetAllTeamsResult
     */
    @WebMethod(operationName = "GetAllTeams", action = "http://xmlsoccer.com/GetAllTeams")
    @WebResult(name = "GetAllTeamsResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetAllTeams", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetAllTeams")
    @ResponseWrapper(localName = "GetAllTeamsResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetAllTeamsResponse")
    public GetAllTeamsResponse.GetAllTeamsResult getAllTeams(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey);

    /**
     * 
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetAllLeaguesResponse.GetAllLeaguesResult
     */
    @WebMethod(operationName = "GetAllLeagues", action = "http://xmlsoccer.com/GetAllLeagues")
    @WebResult(name = "GetAllLeaguesResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetAllLeagues", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetAllLeagues")
    @ResponseWrapper(localName = "GetAllLeaguesResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetAllLeaguesResponse")
    public GetAllLeaguesResponse.GetAllLeaguesResult getAllLeagues(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey);

    /**
     * 
     * @param seasonDateString
     * @param league
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetAllGroupsByLeagueAndSeasonResponse.GetAllGroupsByLeagueAndSeasonResult
     */
    @WebMethod(operationName = "GetAllGroupsByLeagueAndSeason", action = "http://xmlsoccer.com/GetAllGroupsByLeagueAndSeason")
    @WebResult(name = "GetAllGroupsByLeagueAndSeasonResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetAllGroupsByLeagueAndSeason", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetAllGroupsByLeagueAndSeason")
    @ResponseWrapper(localName = "GetAllGroupsByLeagueAndSeasonResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetAllGroupsByLeagueAndSeasonResponse")
    public GetAllGroupsByLeagueAndSeasonResponse.GetAllGroupsByLeagueAndSeasonResult getAllGroupsByLeagueAndSeason(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league,
            @WebParam(name = "seasonDateString", targetNamespace = "http://xmlsoccer.com/")
            String seasonDateString);

    /**
     * 
     * @param seasonDateString
     * @param league
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetLeagueStandingsBySeasonResponse.GetLeagueStandingsBySeasonResult
     */
    @WebMethod(operationName = "GetLeagueStandingsBySeason", action = "http://xmlsoccer.com/GetLeagueStandingsBySeason")
    @WebResult(name = "GetLeagueStandingsBySeasonResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetLeagueStandingsBySeason", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetLeagueStandingsBySeason")
    @ResponseWrapper(localName = "GetLeagueStandingsBySeasonResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetLeagueStandingsBySeasonResponse")
    public GetLeagueStandingsBySeasonResponse.GetLeagueStandingsBySeasonResult getLeagueStandingsBySeason(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league,
            @WebParam(name = "seasonDateString", targetNamespace = "http://xmlsoccer.com/")
            String seasonDateString);

    /**
     * 
     * @param groupId
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetCupStandingsByGroupIdResponse.GetCupStandingsByGroupIdResult
     */
    @WebMethod(operationName = "GetCupStandingsByGroupId", action = "http://xmlsoccer.com/GetCupStandingsByGroupId")
    @WebResult(name = "GetCupStandingsByGroupIdResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetCupStandingsByGroupId", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetCupStandingsByGroupId")
    @ResponseWrapper(localName = "GetCupStandingsByGroupIdResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetCupStandingsByGroupIdResponse")
    public GetCupStandingsByGroupIdResponse.GetCupStandingsByGroupIdResult getCupStandingsByGroupId(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "group_Id", targetNamespace = "http://xmlsoccer.com/")
            int groupId);

    /**
     * 
     * @param seasonDateString
     * @param league
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetAllTeamsByLeagueAndSeasonResponse.GetAllTeamsByLeagueAndSeasonResult
     */
    @WebMethod(operationName = "GetAllTeamsByLeagueAndSeason", action = "http://xmlsoccer.com/GetAllTeamsByLeagueAndSeason")
    @WebResult(name = "GetAllTeamsByLeagueAndSeasonResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetAllTeamsByLeagueAndSeason", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetAllTeamsByLeagueAndSeason")
    @ResponseWrapper(localName = "GetAllTeamsByLeagueAndSeasonResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetAllTeamsByLeagueAndSeasonResponse")
    public GetAllTeamsByLeagueAndSeasonResponse.GetAllTeamsByLeagueAndSeasonResult getAllTeamsByLeagueAndSeason(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league,
            @WebParam(name = "seasonDateString", targetNamespace = "http://xmlsoccer.com/")
            String seasonDateString);

    /**
     * 
     * @param league
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetEarliestMatchDatePerLeagueResponse.GetEarliestMatchDatePerLeagueResult
     */
    @WebMethod(operationName = "GetEarliestMatchDatePerLeague", action = "http://xmlsoccer.com/GetEarliestMatchDatePerLeague")
    @WebResult(name = "GetEarliestMatchDatePerLeagueResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetEarliestMatchDatePerLeague", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetEarliestMatchDatePerLeague")
    @ResponseWrapper(localName = "GetEarliestMatchDatePerLeagueResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetEarliestMatchDatePerLeagueResponse")
    public GetEarliestMatchDatePerLeagueResponse.GetEarliestMatchDatePerLeagueResult getEarliestMatchDatePerLeague(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league);

    /**
     * 
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetLiveScoreResponse.GetLiveScoreResult
     */
    @WebMethod(operationName = "GetLiveScore", action = "http://xmlsoccer.com/GetLiveScore")
    @WebResult(name = "GetLiveScoreResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetLiveScore", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetLiveScore")
    @ResponseWrapper(localName = "GetLiveScoreResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetLiveScoreResponse")
    public GetLiveScoreResponse.GetLiveScoreResult getLiveScore(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey);

    /**
     * 
     * @param league
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetLiveScoreByLeagueResponse.GetLiveScoreByLeagueResult
     */
    @WebMethod(operationName = "GetLiveScoreByLeague", action = "http://xmlsoccer.com/GetLiveScoreByLeague")
    @WebResult(name = "GetLiveScoreByLeagueResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetLiveScoreByLeague", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetLiveScoreByLeague")
    @ResponseWrapper(localName = "GetLiveScoreByLeagueResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetLiveScoreByLeagueResponse")
    public GetLiveScoreByLeagueResponse.GetLiveScoreByLeagueResult getLiveScoreByLeague(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league);

    /**
     * 
     * @param teamId
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetPlayersByTeamResponse.GetPlayersByTeamResult
     */
    @WebMethod(operationName = "GetPlayersByTeam", action = "http://xmlsoccer.com/GetPlayersByTeam")
    @WebResult(name = "GetPlayersByTeamResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetPlayersByTeam", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetPlayersByTeam")
    @ResponseWrapper(localName = "GetPlayersByTeamResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetPlayersByTeamResponse")
    public GetPlayersByTeamResponse.GetPlayersByTeamResult getPlayersByTeam(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "teamId", targetNamespace = "http://xmlsoccer.com/")
            String teamId);

    /**
     * 
     * @param playerId
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetPlayerByIdResponse.GetPlayerByIdResult
     */
    @WebMethod(operationName = "GetPlayerById", action = "http://xmlsoccer.com/GetPlayerById")
    @WebResult(name = "GetPlayerByIdResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetPlayerById", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetPlayerById")
    @ResponseWrapper(localName = "GetPlayerByIdResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetPlayerByIdResponse")
    public GetPlayerByIdResponse.GetPlayerByIdResult getPlayerById(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "playerId", targetNamespace = "http://xmlsoccer.com/")
            int playerId);

    /**
     * 
     * @param teamName
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetTeamResponse.GetTeamResult
     */
    @WebMethod(operationName = "GetTeam", action = "http://xmlsoccer.com/GetTeam")
    @WebResult(name = "GetTeamResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetTeam", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetTeam")
    @ResponseWrapper(localName = "GetTeamResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetTeamResponse")
    public GetTeamResponse.GetTeamResult getTeam(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "teamName", targetNamespace = "http://xmlsoccer.com/")
            String teamName);

    /**
     * 
     * @param fixtureMatchId
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetOddsByFixtureMatchIdResponse.GetOddsByFixtureMatchIdResult
     */
    @WebMethod(operationName = "GetOddsByFixtureMatchId", action = "http://xmlsoccer.com/GetOddsByFixtureMatchId")
    @WebResult(name = "GetOddsByFixtureMatchIdResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetOddsByFixtureMatchId", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetOddsByFixtureMatchId")
    @ResponseWrapper(localName = "GetOddsByFixtureMatchIdResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetOddsByFixtureMatchIdResponse")
    public GetOddsByFixtureMatchIdResponse.GetOddsByFixtureMatchIdResult getOddsByFixtureMatchId(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "fixtureMatch_Id", targetNamespace = "http://xmlsoccer.com/")
            String fixtureMatchId);

    /**
     * 
     * @param fixtureMatchId
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetOddsByFixtureMatchId2Response.GetOddsByFixtureMatchId2Result
     */
    @WebMethod(operationName = "GetOddsByFixtureMatchId2", action = "http://xmlsoccer.com/GetOddsByFixtureMatchId2")
    @WebResult(name = "GetOddsByFixtureMatchId2Result", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetOddsByFixtureMatchId2", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetOddsByFixtureMatchId2")
    @ResponseWrapper(localName = "GetOddsByFixtureMatchId2Response", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetOddsByFixtureMatchId2Response")
    public GetOddsByFixtureMatchId2Response.GetOddsByFixtureMatchId2Result getOddsByFixtureMatchId2(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "fixtureMatch_Id", targetNamespace = "http://xmlsoccer.com/")
            String fixtureMatchId);

    /**
     * 
     * @param fixtureMatchId
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetAllOddsByFixtureMatchIdResponse.GetAllOddsByFixtureMatchIdResult
     */
    @WebMethod(operationName = "GetAllOddsByFixtureMatchId", action = "http://xmlsoccer.com/GetAllOddsByFixtureMatchId")
    @WebResult(name = "GetAllOddsByFixtureMatchIdResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetAllOddsByFixtureMatchId", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetAllOddsByFixtureMatchId")
    @ResponseWrapper(localName = "GetAllOddsByFixtureMatchIdResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetAllOddsByFixtureMatchIdResponse")
    public GetAllOddsByFixtureMatchIdResponse.GetAllOddsByFixtureMatchIdResult getAllOddsByFixtureMatchId(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "fixtureMatch_Id", targetNamespace = "http://xmlsoccer.com/")
            int fixtureMatchId);

    /**
     * 
     * @param league
     * @param apiKey
     * @return
     *     returns pl.com.pablo.xmlsoccer.GetNextMatchOddsByLeagueResponse.GetNextMatchOddsByLeagueResult
     */
    @WebMethod(operationName = "GetNextMatchOddsByLeague", action = "http://xmlsoccer.com/GetNextMatchOddsByLeague")
    @WebResult(name = "GetNextMatchOddsByLeagueResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "GetNextMatchOddsByLeague", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetNextMatchOddsByLeague")
    @ResponseWrapper(localName = "GetNextMatchOddsByLeagueResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.GetNextMatchOddsByLeagueResponse")
    public GetNextMatchOddsByLeagueResponse.GetNextMatchOddsByLeagueResult getNextMatchOddsByLeague(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey,
            @WebParam(name = "league", targetNamespace = "http://xmlsoccer.com/")
            String league);

    /**
     * 
     * @param apiKey
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "CheckApiKey", action = "http://xmlsoccer.com/CheckApiKey")
    @WebResult(name = "CheckApiKeyResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "CheckApiKey", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.CheckApiKey")
    @ResponseWrapper(localName = "CheckApiKeyResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.CheckApiKeyResponse")
    public String checkApiKey(
            @WebParam(name = "ApiKey", targetNamespace = "http://xmlsoccer.com/")
            String apiKey);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ImAlive", action = "http://xmlsoccer.com/ImAlive")
    @WebResult(name = "ImAliveResult", targetNamespace = "http://xmlsoccer.com/")
    @RequestWrapper(localName = "ImAlive", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.ImAlive")
    @ResponseWrapper(localName = "ImAliveResponse", targetNamespace = "http://xmlsoccer.com/", className = "pl.com.pablo.xmlsoccer.ImAliveResponse")
    public String imAlive();

}
