package com.github.pabloo99.xmlsoccer.model.xml;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.08.31 at 11:24:50 PM CEST 
//


import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="Match">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="League" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Round" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="HomeTeam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="HomeTeam_Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="HomeGoals" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="AwayTeam" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="AwayTeam_Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="AwayGoals" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="BetAtHome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="BetAtDraw" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="BetAtAway" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="BetAtHomeLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CentreBetHome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CentreBetDraw" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CentreBetAway" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="CentreBetLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="GameBookersHome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="GameBookersDraw" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="GameBookersAway" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="GameBookersLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="WilliamHill_Home" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="WilliamHill_Draw" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="WilliamHill_Away" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="WilliamHillLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="InterwettenHome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="InterwettenDraw" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="InterwettenAway" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="InterwettenLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="HomeTeamYellowCardDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AwayTeamYellowCardDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="HomeTeamRedCardDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AwayTeamRedCardDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "match"
})
@XmlRootElement(name = "XMLSOCCER.COM")
public class GetFixturesResultXML {

    @XmlElement(name = "Match")
    protected List<Match> match;

    /**
     * Gets the value of the match property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the match property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMatch().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLSOCCERCOM.Match }
     *
     *
     */
    public List<Match> getMatch() {
        if (match == null) {
            match = new ArrayList<Match>();
        }
        return this.match;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="League" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Round" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="HomeTeam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="HomeTeam_Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="HomeGoals" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="AwayTeam" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="AwayTeam_Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="AwayGoals" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="Time" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="Location" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="BetAtHome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="BetAtDraw" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="BetAtAway" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="BetAtHomeLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CentreBetHome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CentreBetDraw" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CentreBetAway" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="CentreBetLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="GameBookersHome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="GameBookersDraw" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="GameBookersAway" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="GameBookersLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="WilliamHill_Home" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="WilliamHill_Draw" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="WilliamHill_Away" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="WilliamHillLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="InterwettenHome" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="InterwettenDraw" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="InterwettenAway" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="InterwettenLink" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="HomeTeamYellowCardDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AwayTeamYellowCardDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="HomeTeamRedCardDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AwayTeamRedCardDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "date",
        "league",
        "round",
        "homeTeam",
        "homeTeamId",
        "homeGoals",
        "awayTeam",
        "awayTeamId",
        "awayGoals",
        "time",
        "location",
        "betAtHome",
        "betAtDraw",
        "betAtAway",
        "betAtHomeLink",
        "centreBetHome",
        "centreBetDraw",
        "centreBetAway",
        "centreBetLink",
        "gameBookersHome",
        "gameBookersDraw",
        "gameBookersAway",
        "gameBookersLink",
        "williamHillHome",
        "williamHillDraw",
        "williamHillAway",
        "williamHillLink",
        "interwettenHome",
        "interwettenDraw",
        "interwettenAway",
        "interwettenLink",
        "homeTeamYellowCardDetails",
        "awayTeamYellowCardDetails",
        "homeTeamRedCardDetails",
        "awayTeamRedCardDetails"
    })
    public static class Match {

        @XmlElement(name = "Id")
        protected int id;
        @XmlElement(name = "Date", required = true)
        @XmlSchemaType(name = "dateTime")
        protected Date date;
        @XmlElement(name = "League", required = true)
        protected String league;
        @XmlElement(name = "Round")
        protected String round;
        @XmlElement(name = "HomeTeam")
        protected String homeTeam;
        @XmlElement(name = "HomeTeam_Id")
        protected int homeTeamId;
        @XmlElement(name = "HomeGoals")
        protected Integer homeGoals;
        @XmlElement(name = "AwayTeam", required = true)
        protected String awayTeam;
        @XmlElement(name = "AwayTeam_Id")
        protected int awayTeamId;
        @XmlElement(name = "AwayGoals")
        protected Integer awayGoals;
        @XmlElement(name = "Time")
        protected String time;
        @XmlElement(name = "Location")
        protected String location;
        @XmlElement(name = "BetAtHome")
        protected String betAtHome;
        @XmlElement(name = "BetAtDraw")
        protected String betAtDraw;
        @XmlElement(name = "BetAtAway")
        protected String betAtAway;
        @XmlElement(name = "BetAtHomeLink")
        protected String betAtHomeLink;
        @XmlElement(name = "CentreBetHome")
        protected String centreBetHome;
        @XmlElement(name = "CentreBetDraw")
        protected String centreBetDraw;
        @XmlElement(name = "CentreBetAway")
        protected String centreBetAway;
        @XmlElement(name = "CentreBetLink")
        protected String centreBetLink;
        @XmlElement(name = "GameBookersHome")
        protected String gameBookersHome;
        @XmlElement(name = "GameBookersDraw")
        protected String gameBookersDraw;
        @XmlElement(name = "GameBookersAway")
        protected String gameBookersAway;
        @XmlElement(name = "GameBookersLink")
        protected String gameBookersLink;
        @XmlElement(name = "WilliamHill_Home")
        protected String williamHillHome;
        @XmlElement(name = "WilliamHill_Draw")
        protected String williamHillDraw;
        @XmlElement(name = "WilliamHill_Away")
        protected String williamHillAway;
        @XmlElement(name = "WilliamHillLink")
        protected String williamHillLink;
        @XmlElement(name = "InterwettenHome")
        protected String interwettenHome;
        @XmlElement(name = "InterwettenDraw")
        protected String interwettenDraw;
        @XmlElement(name = "InterwettenAway")
        protected String interwettenAway;
        @XmlElement(name = "InterwettenLink")
        protected String interwettenLink;
        @XmlElement(name = "HomeTeamYellowCardDetails")
        protected String homeTeamYellowCardDetails;
        @XmlElement(name = "AwayTeamYellowCardDetails")
        protected String awayTeamYellowCardDetails;
        @XmlElement(name = "HomeTeamRedCardDetails")
        protected String homeTeamRedCardDetails;
        @XmlElement(name = "AwayTeamRedCardDetails")
        protected String awayTeamRedCardDetails;

        /**
         * Gets the value of the id property.
         *
         */
        public int getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         *
         */
        public void setId(int value) {
            this.id = value;
        }

        /**
         * Gets the value of the date property.
         *
         * @return
         *     possible object is
         *     {@link javax.xml.datatype.XMLGregorianCalendar }
         *
         */
        public Date getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         *
         * @param value
         *     allowed object is
         *     {@link javax.xml.datatype.XMLGregorianCalendar }
         *     
         */
        public void setDate(Date value) {
            this.date = value;
        }

        /**
         * Gets the value of the league property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLeague() {
            return league;
        }

        /**
         * Sets the value of the league property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLeague(String value) {
            this.league = value;
        }

        /**
         * Gets the value of the round property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public String getRound() {
            return round;
        }

        /**
         * Sets the value of the round property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setRound(String value) {
            this.round = value;
        }

        /**
         * Gets the value of the homeTeam property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeTeam() {
            return homeTeam;
        }

        /**
         * Sets the value of the homeTeam property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeTeam(String value) {
            this.homeTeam = value;
        }

        /**
         * Gets the value of the homeTeamId property.
         * 
         */
        public int getHomeTeamId() {
            return homeTeamId;
        }

        /**
         * Sets the value of the homeTeamId property.
         * 
         */
        public void setHomeTeamId(int value) {
            this.homeTeamId = value;
        }

        /**
         * Gets the value of the homeGoals property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getHomeGoals() {
            return homeGoals;
        }

        /**
         * Sets the value of the homeGoals property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setHomeGoals(Integer value) {
            this.homeGoals = value;
        }

        /**
         * Gets the value of the awayTeam property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayTeam() {
            return awayTeam;
        }

        /**
         * Sets the value of the awayTeam property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayTeam(String value) {
            this.awayTeam = value;
        }

        /**
         * Gets the value of the awayTeamId property.
         * 
         */
        public int getAwayTeamId() {
            return awayTeamId;
        }

        /**
         * Sets the value of the awayTeamId property.
         * 
         */
        public void setAwayTeamId(int value) {
            this.awayTeamId = value;
        }

        /**
         * Gets the value of the awayGoals property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getAwayGoals() {
            return awayGoals;
        }

        /**
         * Sets the value of the awayGoals property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setAwayGoals(Integer value) {
            this.awayGoals = value;
        }

        /**
         * Gets the value of the time property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTime() {
            return time;
        }

        /**
         * Sets the value of the time property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTime(String value) {
            this.time = value;
        }

        /**
         * Gets the value of the location property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLocation() {
            return location;
        }

        /**
         * Sets the value of the location property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLocation(String value) {
            this.location = value;
        }

        /**
         * Gets the value of the betAtHome property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBetAtHome() {
            return betAtHome;
        }

        /**
         * Sets the value of the betAtHome property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBetAtHome(String value) {
            this.betAtHome = value;
        }

        /**
         * Gets the value of the betAtDraw property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBetAtDraw() {
            return betAtDraw;
        }

        /**
         * Sets the value of the betAtDraw property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBetAtDraw(String value) {
            this.betAtDraw = value;
        }

        /**
         * Gets the value of the betAtAway property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBetAtAway() {
            return betAtAway;
        }

        /**
         * Sets the value of the betAtAway property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBetAtAway(String value) {
            this.betAtAway = value;
        }

        /**
         * Gets the value of the betAtHomeLink property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getBetAtHomeLink() {
            return betAtHomeLink;
        }

        /**
         * Sets the value of the betAtHomeLink property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setBetAtHomeLink(String value) {
            this.betAtHomeLink = value;
        }

        /**
         * Gets the value of the centreBetHome property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCentreBetHome() {
            return centreBetHome;
        }

        /**
         * Sets the value of the centreBetHome property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCentreBetHome(String value) {
            this.centreBetHome = value;
        }

        /**
         * Gets the value of the centreBetDraw property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCentreBetDraw() {
            return centreBetDraw;
        }

        /**
         * Sets the value of the centreBetDraw property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCentreBetDraw(String value) {
            this.centreBetDraw = value;
        }

        /**
         * Gets the value of the centreBetAway property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCentreBetAway() {
            return centreBetAway;
        }

        /**
         * Sets the value of the centreBetAway property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCentreBetAway(String value) {
            this.centreBetAway = value;
        }

        /**
         * Gets the value of the centreBetLink property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCentreBetLink() {
            return centreBetLink;
        }

        /**
         * Sets the value of the centreBetLink property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCentreBetLink(String value) {
            this.centreBetLink = value;
        }

        /**
         * Gets the value of the gameBookersHome property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGameBookersHome() {
            return gameBookersHome;
        }

        /**
         * Sets the value of the gameBookersHome property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGameBookersHome(String value) {
            this.gameBookersHome = value;
        }

        /**
         * Gets the value of the gameBookersDraw property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGameBookersDraw() {
            return gameBookersDraw;
        }

        /**
         * Sets the value of the gameBookersDraw property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGameBookersDraw(String value) {
            this.gameBookersDraw = value;
        }

        /**
         * Gets the value of the gameBookersAway property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGameBookersAway() {
            return gameBookersAway;
        }

        /**
         * Sets the value of the gameBookersAway property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGameBookersAway(String value) {
            this.gameBookersAway = value;
        }

        /**
         * Gets the value of the gameBookersLink property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getGameBookersLink() {
            return gameBookersLink;
        }

        /**
         * Sets the value of the gameBookersLink property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setGameBookersLink(String value) {
            this.gameBookersLink = value;
        }

        /**
         * Gets the value of the williamHillHome property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWilliamHillHome() {
            return williamHillHome;
        }

        /**
         * Sets the value of the williamHillHome property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWilliamHillHome(String value) {
            this.williamHillHome = value;
        }

        /**
         * Gets the value of the williamHillDraw property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWilliamHillDraw() {
            return williamHillDraw;
        }

        /**
         * Sets the value of the williamHillDraw property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWilliamHillDraw(String value) {
            this.williamHillDraw = value;
        }

        /**
         * Gets the value of the williamHillAway property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWilliamHillAway() {
            return williamHillAway;
        }

        /**
         * Sets the value of the williamHillAway property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWilliamHillAway(String value) {
            this.williamHillAway = value;
        }

        /**
         * Gets the value of the williamHillLink property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWilliamHillLink() {
            return williamHillLink;
        }

        /**
         * Sets the value of the williamHillLink property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWilliamHillLink(String value) {
            this.williamHillLink = value;
        }

        /**
         * Gets the value of the interwettenHome property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterwettenHome() {
            return interwettenHome;
        }

        /**
         * Sets the value of the interwettenHome property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterwettenHome(String value) {
            this.interwettenHome = value;
        }

        /**
         * Gets the value of the interwettenDraw property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterwettenDraw() {
            return interwettenDraw;
        }

        /**
         * Sets the value of the interwettenDraw property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterwettenDraw(String value) {
            this.interwettenDraw = value;
        }

        /**
         * Gets the value of the interwettenAway property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterwettenAway() {
            return interwettenAway;
        }

        /**
         * Sets the value of the interwettenAway property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterwettenAway(String value) {
            this.interwettenAway = value;
        }

        /**
         * Gets the value of the interwettenLink property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getInterwettenLink() {
            return interwettenLink;
        }

        /**
         * Sets the value of the interwettenLink property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setInterwettenLink(String value) {
            this.interwettenLink = value;
        }

        /**
         * Gets the value of the homeTeamYellowCardDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeTeamYellowCardDetails() {
            return homeTeamYellowCardDetails;
        }

        /**
         * Sets the value of the homeTeamYellowCardDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeTeamYellowCardDetails(String value) {
            this.homeTeamYellowCardDetails = value;
        }

        /**
         * Gets the value of the awayTeamYellowCardDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayTeamYellowCardDetails() {
            return awayTeamYellowCardDetails;
        }

        /**
         * Sets the value of the awayTeamYellowCardDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayTeamYellowCardDetails(String value) {
            this.awayTeamYellowCardDetails = value;
        }

        /**
         * Gets the value of the homeTeamRedCardDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeTeamRedCardDetails() {
            return homeTeamRedCardDetails;
        }

        /**
         * Sets the value of the homeTeamRedCardDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeTeamRedCardDetails(String value) {
            this.homeTeamRedCardDetails = value;
        }

        /**
         * Gets the value of the awayTeamRedCardDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayTeamRedCardDetails() {
            return awayTeamRedCardDetails;
        }

        /**
         * Sets the value of the awayTeamRedCardDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayTeamRedCardDetails(String value) {
            this.awayTeamRedCardDetails = value;
        }

        @Override
        public String toString() {
//            return "Match{" + "id=" + id + ", date=" + date + ", league=" + league + ", round=" + round + ", homeTeam=" + homeTeam + ", homeTeamId=" + homeTeamId + ", homeGoals=" + homeGoals + ", awayTeam=" + awayTeam + ", awayTeamId=" + awayTeamId + ", awayGoals=" + awayGoals + ", time=" + time + ", location=" + location + ", betAtHome=" + betAtHome + ", betAtDraw=" + betAtDraw + ", betAtAway=" + betAtAway + ", betAtHomeLink=" + betAtHomeLink + ", centreBetHome=" + centreBetHome + ", centreBetDraw=" + centreBetDraw + ", centreBetAway=" + centreBetAway + ", centreBetLink=" + centreBetLink + ", gameBookersHome=" + gameBookersHome + ", gameBookersDraw=" + gameBookersDraw + ", gameBookersAway=" + gameBookersAway + ", gameBookersLink=" + gameBookersLink + ", williamHillHome=" + williamHillHome + ", williamHillDraw=" + williamHillDraw + ", williamHillAway=" + williamHillAway + ", williamHillLink=" + williamHillLink + ", interwettenHome=" + interwettenHome + ", interwettenDraw=" + interwettenDraw + ", interwettenAway=" + interwettenAway + ", interwettenLink=" + interwettenLink + ", homeTeamYellowCardDetails=" + homeTeamYellowCardDetails + ", awayTeamYellowCardDetails=" + awayTeamYellowCardDetails + ", homeTeamRedCardDetails=" + homeTeamRedCardDetails + ", awayTeamRedCardDetails=" + awayTeamRedCardDetails + '}';
            return "FIXTURE: " + "  DATE: " + date + "  LEAGUE: " + league + "  HOME TEAM: " + homeTeam + "  AWAY TEAM: " + awayTeam + " TIME: " + time + "  HOME GOALS:" + homeGoals + "  AWAY GOALS: " + awayGoals ;

        }

    }

}
