package com.github.pabloo99.xmlsoccer.model.xml;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.01 at 12:14:56 AM CEST 
//


import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="Match">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="FixtureMatch_Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                   &lt;element name="Round" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="Spectators" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="League" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="HomeTeam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="HomeTeam_Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="HomeCorners" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="HomeGoals" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="HalfTimeHomeGoals" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="HomeShots" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="HomeShotsOnTarget" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="HomeFouls" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="HomeGoalDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="HomeLineupGoalkeeper" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="HomeLineupDefense" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="HomeLineupMidfield" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="HomeLineupForward" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="HomeYellowCards" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="HomeRedCards" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="HomeTeamFormation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AwayTeam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AwayTeam_Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="AwayCorners" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="AwayGoals" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="HalfTimeAwayGoals" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="AwayShots" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="AwayShotsOnTarget" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="AwayFouls" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="AwayGoalDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AwayLineupGoalkeeper" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AwayLineupDefense" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AwayLineupMidfield" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AwayLineupForward" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AwayYellowCards" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="AwayRedCards" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *                   &lt;element name="AwayTeamFormation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="HomeTeamYellowCardDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AwayTeamYellowCardDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="HomeTeamRedCardDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="AwayTeamRedCardDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "match"
})
@XmlRootElement(name = "XMLSOCCER.COM")
public class GetHistoricMatchesResultXML {

    @XmlElement(name = "Match")
    protected List<Match> match;

    /**
     * Gets the value of the match property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the match property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMatch().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLSOCCERCOM.Match }
     *
     *
     */
    public List<Match> getMatch() {
        if (match == null) {
            match = new ArrayList<Match>();
        }
        return this.match;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="FixtureMatch_Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *         &lt;element name="Round" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="Spectators" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="League" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="HomeTeam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="HomeTeam_Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="HomeCorners" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="HomeGoals" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="HalfTimeHomeGoals" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="HomeShots" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="HomeShotsOnTarget" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="HomeFouls" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="HomeGoalDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="HomeLineupGoalkeeper" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="HomeLineupDefense" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="HomeLineupMidfield" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="HomeLineupForward" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="HomeYellowCards" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="HomeRedCards" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="HomeTeamFormation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AwayTeam" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AwayTeam_Id" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="AwayCorners" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="AwayGoals" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="HalfTimeAwayGoals" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="AwayShots" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="AwayShotsOnTarget" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="AwayFouls" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="AwayGoalDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AwayLineupGoalkeeper" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AwayLineupDefense" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AwayLineupMidfield" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AwayLineupForward" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AwayYellowCards" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="AwayRedCards" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
     *         &lt;element name="AwayTeamFormation" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="HomeTeamYellowCardDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AwayTeamYellowCardDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="HomeTeamRedCardDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="AwayTeamRedCardDetails" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "fixtureMatchId",
        "date",
        "round",
        "spectators",
        "league",
        "homeTeam",
        "homeTeamId",
        "homeCorners",
        "homeGoals",
        "halfTimeHomeGoals",
        "homeShots",
        "homeShotsOnTarget",
        "homeFouls",
        "homeGoalDetails",
        "homeLineupGoalkeeper",
        "homeLineupDefense",
        "homeLineupMidfield",
        "homeLineupForward",
        "homeYellowCards",
        "homeRedCards",
        "homeTeamFormation",
        "awayTeam",
        "awayTeamId",
        "awayCorners",
        "awayGoals",
        "halfTimeAwayGoals",
        "awayShots",
        "awayShotsOnTarget",
        "awayFouls",
        "awayGoalDetails",
        "awayLineupGoalkeeper",
        "awayLineupDefense",
        "awayLineupMidfield",
        "awayLineupForward",
        "awayYellowCards",
        "awayRedCards",
        "awayTeamFormation",
        "homeTeamYellowCardDetails",
        "awayTeamYellowCardDetails",
        "homeTeamRedCardDetails",
        "awayTeamRedCardDetails"
    })
    public static class Match {

        @XmlElement(name = "Id")
        protected Integer id;
        @XmlElement(name = "FixtureMatch_Id")
        protected Integer fixtureMatchId;
        @XmlElement(name = "Date")
        @XmlSchemaType(name = "dateTime")
        protected Date date;
        @XmlElement(name = "Round")
        protected Integer round;
        @XmlElement(name = "Spectators")
        protected String spectators;
        @XmlElement(name = "League")
        protected String league;
        @XmlElement(name = "HomeTeam")
        protected String homeTeam;
        @XmlElement(name = "HomeTeam_Id")
        protected Integer homeTeamId;
        @XmlElement(name = "HomeCorners")
        protected Integer homeCorners;
        @XmlElement(name = "HomeGoals")
        protected Integer homeGoals;
        @XmlElement(name = "HalfTimeHomeGoals")
        protected Integer halfTimeHomeGoals;
        @XmlElement(name = "HomeShots")
        protected Integer homeShots;
        @XmlElement(name = "HomeShotsOnTarget")
        protected Integer homeShotsOnTarget;
        @XmlElement(name = "HomeFouls")
        protected Integer homeFouls;
        @XmlElement(name = "HomeGoalDetails")
        protected String homeGoalDetails;
        @XmlElement(name = "HomeLineupGoalkeeper")
        protected String homeLineupGoalkeeper;
        @XmlElement(name = "HomeLineupDefense")
        protected String homeLineupDefense;
        @XmlElement(name = "HomeLineupMidfield")
        protected String homeLineupMidfield;
        @XmlElement(name = "HomeLineupForward")
        protected String homeLineupForward;
        @XmlElement(name = "HomeYellowCards")
        protected Integer homeYellowCards;
        @XmlElement(name = "HomeRedCards")
        protected Integer homeRedCards;
        @XmlElement(name = "HomeTeamFormation")
        protected String homeTeamFormation;
        @XmlElement(name = "AwayTeam")
        protected String awayTeam;
        @XmlElement(name = "AwayTeam_Id")
        protected Integer awayTeamId;
        @XmlElement(name = "AwayCorners")
        protected Integer awayCorners;
        @XmlElement(name = "AwayGoals")
        protected Integer awayGoals;
        @XmlElement(name = "HalfTimeAwayGoals")
        protected Integer halfTimeAwayGoals;
        @XmlElement(name = "AwayShots")
        protected Integer awayShots;
        @XmlElement(name = "AwayShotsOnTarget")
        protected Integer awayShotsOnTarget;
        @XmlElement(name = "AwayFouls")
        protected Integer awayFouls;
        @XmlElement(name = "AwayGoalDetails")
        protected String awayGoalDetails;
        @XmlElement(name = "AwayLineupGoalkeeper")
        protected String awayLineupGoalkeeper;
        @XmlElement(name = "AwayLineupDefense")
        protected String awayLineupDefense;
        @XmlElement(name = "AwayLineupMidfield")
        protected String awayLineupMidfield;
        @XmlElement(name = "AwayLineupForward")
        protected String awayLineupForward;
        @XmlElement(name = "AwayYellowCards")
        protected Integer awayYellowCards;
        @XmlElement(name = "AwayRedCards")
        protected Integer awayRedCards;
        @XmlElement(name = "AwayTeamFormation")
        protected String awayTeamFormation;
        @XmlElement(name = "HomeTeamYellowCardDetails")
        protected String homeTeamYellowCardDetails;
        @XmlElement(name = "AwayTeamYellowCardDetails")
        protected String awayTeamYellowCardDetails;
        @XmlElement(name = "HomeTeamRedCardDetails")
        protected String homeTeamRedCardDetails;
        @XmlElement(name = "AwayTeamRedCardDetails")
        protected String awayTeamRedCardDetails;
        @XmlTransient
        protected String season;

        /**
         * Gets the value of the id property.
         *
         * @return
         *     possible object is
         *     {@link Integer }
         *
         */
        public Integer getId() {
            return id;
        }


        public String getSeason() {
            return season;
        }

        public void setSeason(String season) {
            this.season = season;
        }

        /**
         * Sets the value of the id property.
         *
         * @param value
         *     allowed object is
         *     {@link Integer }
         *
         */
        public void setId(Integer value) {
            this.id = value;
        }

        /**
         * Gets the value of the fixtureMatchId property.
         *
         * @return
         *     possible object is
         *     {@link Integer }
         *
         */
        public Integer getFixtureMatchId() {
            return fixtureMatchId;
        }

        /**
         * Sets the value of the fixtureMatchId property.
         *
         * @param value
         *     allowed object is
         *     {@link Integer }
         *
         */
        public void setFixtureMatchId(Integer value) {
            this.fixtureMatchId = value;
        }

        /**
         * Gets the value of the date property.
         *
         * @return
         *     possible object is
         *     {@link javax.xml.datatype.XMLGregorianCalendar }
         *
         */
        public Date getDate() {
            return date;
        }

        /**
         * Sets the value of the date property.
         *
         * @param value
         *     allowed object is
         *     {@link javax.xml.datatype.XMLGregorianCalendar }
         *     
         */
        public void setDate(Date value) {
            this.date = value;
        }

        /**
         * Gets the value of the round property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getRound() {
            return round;
        }

        /**
         * Sets the value of the round property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setRound(Integer value) {
            this.round = value;
        }

        /**
         * Gets the value of the spectators property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSpectators() {
            return spectators;
        }

        /**
         * Sets the value of the spectators property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSpectators(String value) {
            this.spectators = value;
        }

        /**
         * Gets the value of the league property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLeague() {
            return league;
        }

        /**
         * Sets the value of the league property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLeague(String value) {
            this.league = value;
        }

        /**
         * Gets the value of the homeTeam property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeTeam() {
            return homeTeam;
        }

        /**
         * Sets the value of the homeTeam property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeTeam(String value) {
            this.homeTeam = value;
        }

        /**
         * Gets the value of the homeTeamId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getHomeTeamId() {
            return homeTeamId;
        }

        /**
         * Sets the value of the homeTeamId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setHomeTeamId(Integer value) {
            this.homeTeamId = value;
        }

        /**
         * Gets the value of the homeCorners property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getHomeCorners() {
            return homeCorners;
        }

        /**
         * Sets the value of the homeCorners property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setHomeCorners(Integer value) {
            this.homeCorners = value;
        }

        /**
         * Gets the value of the homeGoals property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getHomeGoals() {
            return homeGoals;
        }

        /**
         * Sets the value of the homeGoals property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setHomeGoals(Integer value) {
            this.homeGoals = value;
        }

        /**
         * Gets the value of the halfTimeHomeGoals property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getHalfTimeHomeGoals() {
            return halfTimeHomeGoals;
        }

        /**
         * Sets the value of the halfTimeHomeGoals property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setHalfTimeHomeGoals(Integer value) {
            this.halfTimeHomeGoals = value;
        }

        /**
         * Gets the value of the homeShots property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getHomeShots() {
            return homeShots;
        }

        /**
         * Sets the value of the homeShots property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setHomeShots(Integer value) {
            this.homeShots = value;
        }

        /**
         * Gets the value of the homeShotsOnTarget property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getHomeShotsOnTarget() {
            return homeShotsOnTarget;
        }

        /**
         * Sets the value of the homeShotsOnTarget property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setHomeShotsOnTarget(Integer value) {
            this.homeShotsOnTarget = value;
        }

        /**
         * Gets the value of the homeFouls property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getHomeFouls() {
            return homeFouls;
        }

        /**
         * Sets the value of the homeFouls property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setHomeFouls(Integer value) {
            this.homeFouls = value;
        }

        /**
         * Gets the value of the homeGoalDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeGoalDetails() {
            return homeGoalDetails;
        }

        /**
         * Sets the value of the homeGoalDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeGoalDetails(String value) {
            this.homeGoalDetails = value;
        }

        /**
         * Gets the value of the homeLineupGoalkeeper property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeLineupGoalkeeper() {
            return homeLineupGoalkeeper;
        }

        /**
         * Sets the value of the homeLineupGoalkeeper property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeLineupGoalkeeper(String value) {
            this.homeLineupGoalkeeper = value;
        }

        /**
         * Gets the value of the homeLineupDefense property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeLineupDefense() {
            return homeLineupDefense;
        }

        /**
         * Sets the value of the homeLineupDefense property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeLineupDefense(String value) {
            this.homeLineupDefense = value;
        }

        /**
         * Gets the value of the homeLineupMidfield property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeLineupMidfield() {
            return homeLineupMidfield;
        }

        /**
         * Sets the value of the homeLineupMidfield property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeLineupMidfield(String value) {
            this.homeLineupMidfield = value;
        }

        /**
         * Gets the value of the homeLineupForward property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeLineupForward() {
            return homeLineupForward;
        }

        /**
         * Sets the value of the homeLineupForward property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeLineupForward(String value) {
            this.homeLineupForward = value;
        }

        /**
         * Gets the value of the homeYellowCards property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getHomeYellowCards() {
            return homeYellowCards;
        }

        /**
         * Sets the value of the homeYellowCards property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setHomeYellowCards(Integer value) {
            this.homeYellowCards = value;
        }

        /**
         * Gets the value of the homeRedCards property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getHomeRedCards() {
            return homeRedCards;
        }

        /**
         * Sets the value of the homeRedCards property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setHomeRedCards(Integer value) {
            this.homeRedCards = value;
        }

        /**
         * Gets the value of the homeTeamFormation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeTeamFormation() {
            return homeTeamFormation;
        }

        /**
         * Sets the value of the homeTeamFormation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeTeamFormation(String value) {
            this.homeTeamFormation = value;
        }

        /**
         * Gets the value of the awayTeam property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayTeam() {
            return awayTeam;
        }

        /**
         * Sets the value of the awayTeam property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayTeam(String value) {
            this.awayTeam = value;
        }

        /**
         * Gets the value of the awayTeamId property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getAwayTeamId() {
            return awayTeamId;
        }

        /**
         * Sets the value of the awayTeamId property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setAwayTeamId(Integer value) {
            this.awayTeamId = value;
        }

        /**
         * Gets the value of the awayCorners property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getAwayCorners() {
            return awayCorners;
        }

        /**
         * Sets the value of the awayCorners property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setAwayCorners(Integer value) {
            this.awayCorners = value;
        }

        /**
         * Gets the value of the awayGoals property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getAwayGoals() {
            return awayGoals;
        }

        /**
         * Sets the value of the awayGoals property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setAwayGoals(Integer value) {
            this.awayGoals = value;
        }

        /**
         * Gets the value of the halfTimeAwayGoals property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getHalfTimeAwayGoals() {
            return halfTimeAwayGoals;
        }

        /**
         * Sets the value of the halfTimeAwayGoals property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setHalfTimeAwayGoals(Integer value) {
            this.halfTimeAwayGoals = value;
        }

        /**
         * Gets the value of the awayShots property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getAwayShots() {
            return awayShots;
        }

        /**
         * Sets the value of the awayShots property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setAwayShots(Integer value) {
            this.awayShots = value;
        }

        /**
         * Gets the value of the awayShotsOnTarget property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getAwayShotsOnTarget() {
            return awayShotsOnTarget;
        }

        /**
         * Sets the value of the awayShotsOnTarget property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setAwayShotsOnTarget(Integer value) {
            this.awayShotsOnTarget = value;
        }

        /**
         * Gets the value of the awayFouls property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getAwayFouls() {
            return awayFouls;
        }

        /**
         * Sets the value of the awayFouls property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setAwayFouls(Integer value) {
            this.awayFouls = value;
        }

        /**
         * Gets the value of the awayGoalDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayGoalDetails() {
            return awayGoalDetails;
        }

        /**
         * Sets the value of the awayGoalDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayGoalDetails(String value) {
            this.awayGoalDetails = value;
        }

        /**
         * Gets the value of the awayLineupGoalkeeper property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayLineupGoalkeeper() {
            return awayLineupGoalkeeper;
        }

        /**
         * Sets the value of the awayLineupGoalkeeper property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayLineupGoalkeeper(String value) {
            this.awayLineupGoalkeeper = value;
        }

        /**
         * Gets the value of the awayLineupDefense property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayLineupDefense() {
            return awayLineupDefense;
        }

        /**
         * Sets the value of the awayLineupDefense property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayLineupDefense(String value) {
            this.awayLineupDefense = value;
        }

        /**
         * Gets the value of the awayLineupMidfield property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayLineupMidfield() {
            return awayLineupMidfield;
        }

        /**
         * Sets the value of the awayLineupMidfield property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayLineupMidfield(String value) {
            this.awayLineupMidfield = value;
        }

        /**
         * Gets the value of the awayLineupForward property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayLineupForward() {
            return awayLineupForward;
        }

        /**
         * Sets the value of the awayLineupForward property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayLineupForward(String value) {
            this.awayLineupForward = value;
        }

        /**
         * Gets the value of the awayYellowCards property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getAwayYellowCards() {
            return awayYellowCards;
        }

        /**
         * Sets the value of the awayYellowCards property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setAwayYellowCards(Integer value) {
            this.awayYellowCards = value;
        }

        /**
         * Gets the value of the awayRedCards property.
         * 
         * @return
         *     possible object is
         *     {@link Integer }
         *     
         */
        public Integer getAwayRedCards() {
            return awayRedCards;
        }

        /**
         * Sets the value of the awayRedCards property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integer }
         *     
         */
        public void setAwayRedCards(Integer value) {
            this.awayRedCards = value;
        }

        /**
         * Gets the value of the awayTeamFormation property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayTeamFormation() {
            return awayTeamFormation;
        }

        /**
         * Sets the value of the awayTeamFormation property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayTeamFormation(String value) {
            this.awayTeamFormation = value;
        }

        /**
         * Gets the value of the homeTeamYellowCardDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeTeamYellowCardDetails() {
            return homeTeamYellowCardDetails;
        }

        /**
         * Sets the value of the homeTeamYellowCardDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeTeamYellowCardDetails(String value) {
            this.homeTeamYellowCardDetails = value;
        }

        /**
         * Gets the value of the awayTeamYellowCardDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayTeamYellowCardDetails() {
            return awayTeamYellowCardDetails;
        }

        /**
         * Sets the value of the awayTeamYellowCardDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayTeamYellowCardDetails(String value) {
            this.awayTeamYellowCardDetails = value;
        }

        /**
         * Gets the value of the homeTeamRedCardDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getHomeTeamRedCardDetails() {
            return homeTeamRedCardDetails;
        }

        /**
         * Sets the value of the homeTeamRedCardDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setHomeTeamRedCardDetails(String value) {
            this.homeTeamRedCardDetails = value;
        }

        /**
         * Gets the value of the awayTeamRedCardDetails property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAwayTeamRedCardDetails() {
            return awayTeamRedCardDetails;
        }

        /**
         * Sets the value of the awayTeamRedCardDetails property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAwayTeamRedCardDetails(String value) {
            this.awayTeamRedCardDetails = value;
        }

        @Override
        public String toString() {
            //return "Match{" + "id=" + id + ", fixtureMatchId=" + fixtureMatchId + ", date=" + date + ", round=" + round + ", spectators=" + spectators + ", league=" + league + ", homeTeam=" + homeTeam + ", homeTeamId=" + homeTeamId + ", homeCorners=" + homeCorners + ", homeGoals=" + homeGoals + ", halfTimeHomeGoals=" + halfTimeHomeGoals + ", homeShots=" + homeShots + ", homeShotsOnTarget=" + homeShotsOnTarget + ", homeFouls=" + homeFouls + ", homeGoalDetails=" + homeGoalDetails + ", homeLineupGoalkeeper=" + homeLineupGoalkeeper + ", homeLineupDefense=" + homeLineupDefense + ", homeLineupMidfield=" + homeLineupMidfield + ", homeLineupForward=" + homeLineupForward + ", homeYellowCards=" + homeYellowCards + ", homeRedCards=" + homeRedCards + ", homeTeamFormation=" + homeTeamFormation + ", awayTeam=" + awayTeam + ", awayTeamId=" + awayTeamId + ", awayCorners=" + awayCorners + ", awayGoals=" + awayGoals + ", halfTimeAwayGoals=" + halfTimeAwayGoals + ", awayShots=" + awayShots + ", awayShotsOnTarget=" + awayShotsOnTarget + ", awayFouls=" + awayFouls + ", awayGoalDetails=" + awayGoalDetails + ", awayLineupGoalkeeper=" + awayLineupGoalkeeper + ", awayLineupDefense=" + awayLineupDefense + ", awayLineupMidfield=" + awayLineupMidfield + ", awayLineupForward=" + awayLineupForward + ", awayYellowCards=" + awayYellowCards + ", awayRedCards=" + awayRedCards + ", awayTeamFormation=" + awayTeamFormation + ", homeTeamYellowCardDetails=" + homeTeamYellowCardDetails + ", awayTeamYellowCardDetails=" + awayTeamYellowCardDetails + ", homeTeamRedCardDetails=" + homeTeamRedCardDetails + ", awayTeamRedCardDetails=" + awayTeamRedCardDetails + '}';
            return "MATCH: " + "  DATE: " + date + "  LEAGUE: " + league + "  HOME TEAM: " + homeTeam + "  AWAY TEAM: " + awayTeam + "  HOME GOALS:" + homeGoals + "  AWAY GOALS: " + awayGoals ;
        }

    }

}
