package com.github.pabloo99.xmlsoccer.model.xml;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.04.10 at 10:03:21 PM CEST 
//


import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Player" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                   &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
 *                   &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Position" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Team_Id" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="PlayerNumber" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
 *                   &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="DateOfSigning" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="Signing" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AccountInformation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "player",
    "accountInformation"
})
@XmlRootElement(name = "XMLSOCCER.COM")
public class GetPlayersByTeamResultXML {

    @XmlElement(name = "Player")
    protected List<Player> player;
    @XmlElement(name = "AccountInformation", required = true)
    protected String accountInformation;

    /**
     * Gets the value of the player property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the player property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlayer().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link XMLSOCCERCOM.Player }
     *
     *
     */
    public List<Player> getPlayer() {
        if (player == null) {
            player = new ArrayList<Player>();
        }
        return this.player;
    }

    /**
     * Gets the value of the accountInformation property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAccountInformation() {
        return accountInformation;
    }

    /**
     * Sets the value of the accountInformation property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAccountInformation(String value) {
        this.accountInformation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     *
     * <p>The following schema fragment specifies the expected content contained within this class.
     *
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="Weight" type="{http://www.w3.org/2001/XMLSchema}float" minOccurs="0"/>
     *         &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Position" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Team_Id" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="PlayerNumber" type="{http://www.w3.org/2001/XMLSchema}byte" minOccurs="0"/>
     *         &lt;element name="DateOfBirth" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="DateOfSigning" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="Signing" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     *
     *
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "name",
        "height",
        "weight",
        "nationality",
        "position",
        "teamId",
        "playerNumber",
        "dateOfBirth",
        "dateOfSigning",
        "signing"
    })
    public static class Player {

        @XmlElement(name = "Id")
        protected Integer id;
        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "Height")
        protected Double height;
        @XmlElement(name = "Weight")
        protected Double weight;
        @XmlElement(name = "Nationality", required = true)
        protected String nationality;
        @XmlElement(name = "Position", required = true)
        protected String position;
        @XmlElement(name = "Team_Id")
        protected Integer teamId;
        @XmlElement(name = "PlayerNumber")
        protected Integer playerNumber;
        @XmlElement(name = "DateOfBirth", required = true)
        @XmlSchemaType(name = "dateTime")
        protected Date dateOfBirth;
        @XmlElement(name = "DateOfSigning", required = true)
        @XmlSchemaType(name = "dateTime")
        protected Date dateOfSigning;
        @XmlElement(name = "Signing", required = true)
        protected String signing;

        /**
         * Gets the value of the id property.
         *
         */
        public Integer getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         *
         */
        public void setId(Integer value) {
            this.id = value;
        }

        /**
         * Gets the value of the name property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the height property.
         *
         * @return
         *     possible object is
         *     {@link Double }
         *
         */
        public Double getHeight() {
            return height;
        }

        /**
         * Sets the value of the height property.
         *
         * @param value
         *     allowed object is
         *     {@link Double }
         *
         */
        public void setHeight(Double value) {
            this.height = value;
        }

        /**
         * Gets the value of the weight property.
         *
         * @return
         *     possible object is
         *     {@link Double }
         *
         */
        public Double getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         *
         * @param value
         *     allowed object is
         *     {@link Double }
         *
         */
        public void setWeight(Double value) {
            this.weight = value;
        }

        /**
         * Gets the value of the nationality property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getNationality() {
            return nationality;
        }

        /**
         * Sets the value of the nationality property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setNationality(String value) {
            this.nationality = value;
        }

        /**
         * Gets the value of the position property.
         *
         * @return
         *     possible object is
         *     {@link String }
         *
         */
        public String getPosition() {
            return position;
        }

        /**
         * Sets the value of the position property.
         *
         * @param value
         *     allowed object is
         *     {@link String }
         *
         */
        public void setPosition(String value) {
            this.position = value;
        }

        /**
         * Gets the value of the teamId property.
         *
         */
        public Integer getTeamId() {
            return teamId;
        }

        /**
         * Sets the value of the teamId property.
         *
         */
        public void setTeamId(Integer value) {
            this.teamId = value;
        }

        /**
         * Gets the value of the playerNumber property.
         *
         * @return
         *     possible object is
         *     {@link Byte }
         *
         */
        public Integer getPlayerNumber() {
            return playerNumber;
        }

        /**
         * Sets the value of the playerNumber property.
         *
         * @param value
         *     allowed object is
         *     {@link Byte }
         *
         */
        public void setPlayerNumber(Integer value) {
            this.playerNumber = value;
        }

        /**
         * Gets the value of the dateOfBirth property.
         *
         * @return
         *     possible object is
         *     {@link javax.xml.datatype.XMLGregorianCalendar }
         *
         */
        public Date getdateOfBirth() {
            return dateOfBirth;
        }

        /**
         * Sets the value of the dateOfBirth property.
         *
         * @param value
         *     allowed object is
         *     {@link javax.xml.datatype.XMLGregorianCalendar }
         *
         */
        public void setdateOfBirth(Date value) {
            this.dateOfBirth = value;
        }

        /**
         * Gets the value of the dateOfSigning property.
         *
         * @return
         *     possible object is
         *     {@link javax.xml.datatype.XMLGregorianCalendar }
         *
         */
        public Date getdateOfSigning() {
            return dateOfSigning;
        }

        /**
         * Sets the value of the dateOfSigning property.
         *
         * @param value
         *     allowed object is
         *     {@link javax.xml.datatype.XMLGregorianCalendar }
         *     
         */
        public void setdateOfSigning(Date value) {
            this.dateOfSigning = value;
        }

        /**
         * Gets the value of the signing property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSigning() {
            return signing;
        }

        /**
         * Sets the value of the signing property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSigning(String value) {
            this.signing = value;
        }

        @Override
        public String toString() {
            return "Player{" + "id=" + id + ", name=" + name + ", height=" + height + ", weight=" + weight + ", nationality=" + nationality + ", position=" + position + ", teamId=" + teamId + ", playerNumber=" + playerNumber + ", dateOfBirth=" + dateOfBirth + ", dateOfSigning=" + dateOfSigning + ", signing=" + signing + '}';
        }
        
        

    }

}
