package com.github.pabloo99.xmlsoccer.model.xml;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.09.01 at 08:08:36 AM CEST 
//


import javax.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Team">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Stadium" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Website" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="WikiPageUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *                   &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AccountInformation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "team",
    "accountInformation"
})
@XmlRootElement(name = "XMLSOCCER.COM")
public class GetTeamResultXML {

    @XmlElement(name = "Team", required = true)
    protected GetTeamResultXML.Team team;
    @XmlElement(name = "AccountInformation", required = true)
    protected String accountInformation;

    /**
     * Gets the value of the team property.
     *
     * @return
     *     possible object is
     *     {@link XMLSOCCERCOM.Team }
     *
     */
    public GetTeamResultXML.Team getTeam() {
        return team;
    }

    /**
     * Sets the value of the team property.
     *
     * @param value
     *     allowed object is
     *     {@link XMLSOCCERCOM.Team }
     *
     */
    public void setTeam(GetTeamResultXML.Team value) {
        this.team = value;
    }

    /**
     * Gets the value of the accountInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountInformation() {
        return accountInformation;
    }

    /**
     * Sets the value of the accountInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountInformation(String value) {
        this.accountInformation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Id" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Stadium" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Website" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="WikiPageUrl" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
     *         &lt;element name="Country" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "id",
        "name",
        "stadium",
        "website",
        "wikiPageUrl",
        "country"
    })
    public static class Team {

        @XmlElement(name = "Id")
        protected short id;
        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "Stadium", required = true)
        protected String stadium;
        @XmlElement(name = "Website", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String website;
        @XmlElement(name = "WikiPageUrl", required = true)
        @XmlSchemaType(name = "anyURI")
        protected String wikiPageUrl;
        @XmlElement(name = "Country", required = true)
        protected String country;

        /**
         * Gets the value of the id property.
         * 
         */
        public short getId() {
            return id;
        }

        /**
         * Sets the value of the id property.
         * 
         */
        public void setId(short value) {
            this.id = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the stadium property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getStadium() {
            return stadium;
        }

        /**
         * Sets the value of the stadium property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setStadium(String value) {
            this.stadium = value;
        }

        /**
         * Gets the value of the website property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWebsite() {
            return website;
        }

        /**
         * Sets the value of the website property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWebsite(String value) {
            this.website = value;
        }

        /**
         * Gets the value of the wikiPageUrl property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getWikiPageUrl() {
            return wikiPageUrl;
        }

        /**
         * Sets the value of the wikiPageUrl property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setWikiPageUrl(String value) {
            this.wikiPageUrl = value;
        }

        /**
         * Gets the value of the country property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getCountry() {
            return country;
        }

        /**
         * Sets the value of the country property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setCountry(String value) {
            this.country = value;
        }

        @Override
        public String toString() {
            return "Team{" + "id=" + id + ", name=" + name + ", stadium=" + stadium + ", website=" + website + ", wikiPageUrl=" + wikiPageUrl + ", country=" + country + '}';
        }

    }

}
