package com.github.pabloo99.xmlsoccer.model.xml;//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.05 at 09:50:57 PM CET 
//


import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Topscorer" maxOccurs="unbounded" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Rank" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="TeamName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Team_Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Goals" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="FirstScorer" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="Penalties" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                   &lt;element name="MissedPenalties" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="AccountInformation" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "topscorer",
    "accountInformation"
})
@XmlRootElement(name = "XMLSOCCER.COM")
public class GetTopScorersResultXML {

    @XmlElement(name = "Topscorer")
    protected List<Topscorer> topscorer;
    @XmlElement(name = "AccountInformation", required = true)
    protected String accountInformation;

    /**
     * Gets the value of the topscorer property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the topscorer property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTopscorer().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GetTopScorersResultXML.Topscorer }
     *
     *
     */
    public List<Topscorer> getTopscorer() {
        if (topscorer == null) {
            topscorer = new ArrayList<Topscorer>();
        }
        return this.topscorer;
    }

    /**
     * Gets the value of the accountInformation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccountInformation() {
        return accountInformation;
    }

    /**
     * Sets the value of the accountInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccountInformation(String value) {
        this.accountInformation = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Rank" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="TeamName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Team_Id" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Nationality" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Goals" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="FirstScorer" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="Penalties" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *         &lt;element name="MissedPenalties" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "rank",
        "name",
        "teamName",
        "teamId",
        "nationality",
        "goals",
        "firstScorer",
        "penalties",
        "missedPenalties"
    })
    public static class Topscorer {

        @XmlElement(name = "Rank")
        protected int rank;
        @XmlElement(name = "Name", required = true)
        protected String name;
        @XmlElement(name = "TeamName", required = true)
        protected String teamName;
        @XmlElement(name = "Team_Id")
        protected int teamId;
        @XmlElement(name = "Nationality", required = true)
        protected String nationality;
        @XmlElement(name = "Goals")
        protected int goals;
        @XmlElement(name = "FirstScorer")
        protected int firstScorer;
        @XmlElement(name = "Penalties")
        protected int penalties;
        @XmlElement(name = "MissedPenalties")
        protected int missedPenalties;
        @XmlTransient
        protected String leagueName;
        @XmlTransient
        protected String season;
        @XmlTransient
        protected int id;

        public String getSeason() {
            return season;
        }

        public void setSeason(String season) {
            this.season = season;
        }
        
        public String getLeagueName() {
            return leagueName;
        }

        public void setLeagueName(String league_name) {
            this.leagueName = league_name;
        }

        public int getId() {
            return id;
        }

        public void setId(int id) {
            this.id = id;
        }
        /**
         * Gets the value of the rank property.
         * 
         */
        public int getRank() {
            return rank;
        }

        /**
         * Sets the value of the rank property.
         * 
         */
        public void setRank(int value) {
            this.rank = value;
        }

        /**
         * Gets the value of the name property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getName() {
            return name;
        }

        /**
         * Sets the value of the name property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setName(String value) {
            this.name = value;
        }

        /**
         * Gets the value of the teamName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTeamName() {
            return teamName;
        }

        /**
         * Sets the value of the teamName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTeamName(String value) {
            this.teamName = value;
        }

        /**
         * Gets the value of the teamId property.
         * 
         */
        public int getTeamId() {
            return teamId;
        }

        /**
         * Sets the value of the teamId property.
         * 
         */
        public void setTeamId(int value) {
            this.teamId = value;
        }

        /**
         * Gets the value of the nationality property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNationality() {
            return nationality;
        }

        /**
         * Sets the value of the nationality property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNationality(String value) {
            this.nationality = value;
        }

        /**
         * Gets the value of the goals property.
         * 
         */
        public int getGoals() {
            return goals;
        }

        /**
         * Sets the value of the goals property.
         * 
         */
        public void setGoals(int value) {
            this.goals = value;
        }

        /**
         * Gets the value of the firstScorer property.
         * 
         */
        public int getFirstScorer() {
            return firstScorer;
        }

        /**
         * Sets the value of the firstScorer property.
         * 
         */
        public void setFirstScorer(int value) {
            this.firstScorer = value;
        }

        /**
         * Gets the value of the penalties property.
         * 
         */
        public int getPenalties() {
            return penalties;
        }

        /**
         * Sets the value of the penalties property.
         * 
         */
        public void setPenalties(int value) {
            this.penalties = value;
        }

        /**
         * Gets the value of the missedPenalties property.
         * 
         */
        public int getMissedPenalties() {
            return missedPenalties;
        }

        /**
         * Sets the value of the missedPenalties property.
         * 
         */
        public void setMissedPenalties(int value) {
            this.missedPenalties = value;
        }

        @Override
        public String toString() {
            //return "Topscorer{" + "rank=" + rank + ", name=" + name + ", teamName=" + teamName + ", teamId=" + teamId + ", nationality=" + nationality + ", goals=" + goals + ", firstScorer=" + firstScorer + ", penalties=" + penalties + ", missedPenalties=" + missedPenalties + ", leagueName=" + leagueName + ", season=" + season + ", id=" + id + '}';
            return "SCORER: " + "  RANK: " + rank + "  NAME: " + name + "  TEAM: " + teamName + "  NATIONALITY: " + nationality + "  GOALS: " + goals + "  PENALTIES: " + penalties + "  LEAGUE: " + leagueName + "  SEASON: " + season;
        }
        
        

    }

}
